"""Builds the OpenXR libvrapi.so and an Echo VR Quest APK that uses it.

    python build.py --apk <echo.apk> --ks <keystore> [--ks-pass android] [--ks-type PKCS12] [--out <out.apk>]
    python build.py --lib-only

1. The Khronos OpenXR loader for Android (libopenxr_loader.so), built once from the
   OpenXR SDK source with CMake (OPENXR_SDK, default: EchoXR's xr/OpenXR-SDK checkout).
2. unimplemented.c: a stub for each VrApi export the runtime doesn't implement.
3. NDK clang -> build/libvrapi.so (exports exactly VrApi's 114 functions).
4. APK: the patcher's changes (patcher/patch.py changes(): libvrapi.so replaced,
   libopenxr_loader.so added, manifest made Lepton-ready), signed with your key.
   Start from an APK without the logger (Meta's libvrapi.so in place).
"""
import argparse
import os
import re
import sys
import zipfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(ROOT, "tools"))
import apkpack  # noqa: E402

BUILD = os.path.join(ROOT, "build")
OPENXR_SDK = os.environ.get("OPENXR_SDK", os.path.join(ROOT, "..", "EchoVR-Hand-Tracking", "xr", "OpenXR-SDK"))
NINJA = os.environ.get("NINJA", r"J:\vs2026\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.exe")


def build_loader():
    out = os.path.join(BUILD, "openxr-loader")
    so = os.path.join(out, "src", "loader", "libopenxr_loader.so")
    if not os.path.exists(so):
        ndk = apkpack.newest(os.path.join(apkpack.SDK, "ndk"))
        os.makedirs(out, exist_ok=True)
        apkpack.run(["cmake", "-G", "Ninja", f"-DCMAKE_MAKE_PROGRAM={NINJA}",
                     f"-DCMAKE_TOOLCHAIN_FILE={ndk}/build/cmake/android.toolchain.cmake",
                     "-DANDROID_ABI=arm64-v8a", f"-DANDROID_PLATFORM={apkpack.API}", "-DANDROID_STL=c++_static",
                     "-DCMAKE_BUILD_TYPE=Release", "-DDYNAMIC_LOADER=ON", "-DBUILD_TESTS=OFF",
                     "-DBUILD_API_LAYERS=OFF", "-DBUILD_CONFORMANCE_TESTS=OFF", OPENXR_SDK], cwd=out)
        apkpack.run(["cmake", "--build", ".", "--target", "openxr_loader"], cwd=out)
    stripped = os.path.join(BUILD, "libopenxr_loader.so")
    apkpack.run([os.path.join(apkpack.ndk_bin(), "llvm-strip.exe"), "--strip-unneeded", so, "-o", stripped])
    return stripped


def write_unimplemented():
    src = open(os.path.join(HERE, "vrapi_openxr.cpp"), encoding="utf-8").read()
    done = set(re.findall(r"^EXPORT [^(]*?\b(\w+)\(", src, re.M)) | {"_Z26VRAPI_LOADER_API_LEVEL_V23v"}
    exports = [l.strip() for l in open(os.path.join(ROOT, "logger", "exports.txt")) if l.strip()]
    todo = [e for e in exports if e not in done]
    path = os.path.join(BUILD, "unimplemented.c")
    with open(path, "w", newline="\n") as f:
        f.write("// Generated by runtime/build.py: VrApi exports Echo VR doesn't use. Each logs once and returns 0.\n")
        f.write("#include <android/log.h>\n#define E __attribute__((visibility(\"default\")))\n")
        f.write("static void Unimplemented(const char* n, int* seen) {\n"
                "    if (!*seen) { *seen = 1; __android_log_print(ANDROID_LOG_WARN, \"EchoQuestXR\", \"%s isn't implemented\", n); }\n}\n")
        for n in todo:
            f.write(f"E long long {n}(void) {{ static int s; Unimplemented(\"{n}\", &s); return 0; }}\n")
    print(f"{len(done)} implemented, {len(todo)} stubs -> {path}")
    return path


def build_lib(loader):
    os.makedirs(BUILD, exist_ok=True)
    stubs = write_unimplemented()
    bin_ = apkpack.ndk_bin()
    lib = os.path.join(BUILD, "libvrapi.so")
    inc = os.path.join(OPENXR_SDK, "include")
    common = [f"--target=aarch64-linux-android{apkpack.API}", "-fPIC", "-O2", "-Wall", "-Wextra",
              "-Wno-unused-parameter", "-Wno-missing-field-initializers", "-fvisibility=hidden", f"-I{inc}"]
    stubs_o = os.path.join(BUILD, "unimplemented.o")   # C, so the exports keep their plain names
    apkpack.run([os.path.join(bin_, "clang.exe"), *common, "-c", stubs, "-o", stubs_o])
    apkpack.run([os.path.join(bin_, "clang++.exe"), *common, "-std=c++17", "-shared", "-static-libstdc++",
                 os.path.join(HERE, "vrapi_openxr.cpp"), stubs_o,
                 "-Wl,-soname,libvrapi.so", "-Wl,--no-undefined", "-Wl,-z,max-page-size=16384",
                 "-Wl,--exclude-libs,ALL",   # keep the static C++ runtime private (Echo has its own)
                 loader, "-lvulkan", "-llog", "-o", lib])
    apkpack.run([os.path.join(bin_, "llvm-strip.exe"), "--strip-unneeded", lib])
    n = apkpack.check_exports(lib, os.path.join(ROOT, "logger", "exports.txt"))
    print(f"built {lib} ({os.path.getsize(lib) // 1024} KB, {n} exports match libvrapi.so)")
    return lib


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--apk")
    ap.add_argument("--out")
    ap.add_argument("--ks", help="keystore the installed APK was signed with")
    ap.add_argument("--ks-pass", default="android")
    ap.add_argument("--ks-type", default="PKCS12", help="PKCS12 or JKS")
    ap.add_argument("--lib-only", action="store_true")
    ap.add_argument("--data-dir", help="game data folder instead of /sdcard/Android/media/<package> (as patch.py --frame)")
    ap.add_argument("--frame-fixes", action="store_true", help="the Steam Frame build's Vulkan fixes (as patch.py --frame)")
    a = ap.parse_args()
    loader = build_loader()
    lib = build_lib(loader)
    if a.lib_only:
        return
    if not a.apk or not a.ks:
        sys.exit("--apk and --ks are needed to build the APK (or use --lib-only)")
    with zipfile.ZipFile(a.apk) as z:
        if apkpack.LIB + "libvrapi_real.so" in z.namelist():
            sys.exit("this APK has the logger in it -- start from one with Meta's libvrapi.so")
    out = a.out or os.path.join(BUILD, os.path.splitext(os.path.basename(a.apk))[0] + "_openxr.apk")
    # exactly the patcher's changes (libraries + manifest), signed with your key instead
    sys.path.insert(0, os.path.join(ROOT, "patcher"))
    import patch  # noqa: E402
    apkpack.repack(a.apk, out, patch.changes(a.apk, BUILD, data_dir=a.data_dir, frame_fixes=a.frame_fixes), a.ks, a.ks_pass, a.ks_type)


if __name__ == "__main__":
    main()
