// EchoQuestXR Platform SDK stand-in -- libovrplatformloader.so for the Steam Frame build.
//
// Meta's libovrplatformloader.so starts the Platform SDK by binding to Horizon OS's
// com.oculus.platformsdkruntime; when that isn't installed (Lepton on Steam Frame) it tries
// to open com.oculus.systemactivities' error screen, fails, and throws OVRPlatformException,
// which aborts Echo the moment it creates its OVR provider (libpnsovr.so):
//   OVRPlatform-Loader: platformSDK_Initialize: Failed to load PlatformSDK driver (-1)!
//   OVRPlatform-Loader: DisplayErrorAndExit: Failed to launch SystemActivities
//
// This stand-in exports the same C functions and answers locally. What Echo's OVR provider
// (libpnsovr.so, build 4987566) does with the answers:
//   ovr_PlatformInitializeAndroid      0 (success); anything else stops Echo
//   entitlement check                  a reply that isn't an error; an error reply makes
//                                      Echo exit (HardExit(1) in the provider's Update)
//   logged-in user, org-scoped ID,     replies with this stand-in's user; Echo logs in to the
//   access token, user proof           community servers with its own config.json, and the
//                                      community build hard-codes the app-scoped user ID
//   friends, purchases, invites,       empty lists
//   rich presence
//   rooms, invite/friend/checkout      an error reply ("not available"): Echo logs it and
//   panels                             carries on (its error handlers only retry when the
//                                      error text is JSON saying is_transient)
//   microphone                         real: AAudio capture (see ovr_Microphone_Create)
//   VoIP, P2P packets                  handles that produce no data
// Replies arrive through ovr_PopMessage on the next poll, as they would from Meta's.
// Every other export of Meta's loader (ovrplatform_exports.txt) is a stub generated by
// runtime/build.py that logs once and returns 0.
//
// Logs to logcat under EchoQuestXR ("Platform SDK: ...").
#include <aaudio/AAudio.h>
#include <math.h>
#include <android/log.h>
#include <pthread.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#define TAG "EchoQuestXR"
#define LOG(...) __android_log_print(ANDROID_LOG_INFO, TAG, __VA_ARGS__)
#define EXPORT __attribute__((visibility("default")))
// logs the first call of each function
#define ONCE(name) do { static int seen_; if (!seen_) { seen_ = 1; LOG("Platform SDK: %s (stand-in)", name); } } while (0)

typedef uint64_t ovrRequest;
typedef uint64_t ovrID;

// The app-scoped user ID and name this stand-in reports. Echo's community build doesn't use
// them to log in (it hard-codes the ID; config.json does the login).
static const ovrID kUserID = 0x4563686f51585231ull;   // "EchoQXR1"
static const char kUserName[] = "EchoQuestXR";
static const char kNotAvailable[] = "Meta's Platform SDK isn't available on this headset (EchoQuestXR stand-in)";

// ovrMessage_Entitlement_GetIsViewerEntitled: the one reply type Echo's provider checks
// (libpnsovr.so Update: movz/movk 0x186b58b1).
#define MESSAGE_ENTITLEMENT 0x186B58B1u

// Every opaque object Echo reads (user, room, arrays, launch details, ...) is this one empty
// block: its accessors below answer with no data, the user's ID and name, or "".
static uint64_t g_empty[32];
static uint64_t g_error[4];
static char g_nonce[33];
static int g_initialized;

typedef struct Message {
    struct Message* next;
    uint32_t type;
    ovrRequest id;
    bool error;
    const char* text;
} Message;

static pthread_mutex_t g_lock = PTHREAD_MUTEX_INITIALIZER;
static Message* g_head;
static Message* g_tail;
static ovrRequest g_next_id = 1;

static ovrRequest Reply(uint32_t type, bool error, const char* text) {
    Message* m = calloc(1, sizeof(Message));
    pthread_mutex_lock(&g_lock);
    ovrRequest id = g_next_id++;
    if (m) {
        m->type = type;
        m->id = id;
        m->error = error;
        m->text = text;
        if (g_tail) g_tail->next = m; else g_head = m;
        g_tail = m;
    }
    pthread_mutex_unlock(&g_lock);
    return id;
}

// ---------------------------------------------------------------------------
// startup and messages
// ---------------------------------------------------------------------------
EXPORT int ovr_PlatformInitializeAndroid(const char* appId, void* activity, void* jni) {
    if (!g_initialized) {
        struct timespec t;
        clock_gettime(CLOCK_REALTIME, &t);
        srand((unsigned)(t.tv_nsec ^ t.tv_sec));
        for (int i = 0; i < 32; i++) g_nonce[i] = "0123456789abcdef"[rand() & 15];
        g_initialized = 1;
    }
    LOG("Platform SDK: ovr_PlatformInitializeAndroid(app %s): started (stand-in, no Meta services)", appId ? appId : "?");
    return 0;   // ovrPlatformInitialize_Success
}

EXPORT bool ovr_IsPlatformInitialized(void) { return g_initialized; }
EXPORT ovrID ovr_GetLoggedInUserID(void) { return kUserID; }

EXPORT Message* ovr_PopMessage(void) {
    pthread_mutex_lock(&g_lock);
    Message* m = g_head;
    if (m) {
        g_head = m->next;
        if (!g_head) g_tail = NULL;
        m->next = NULL;
    }
    pthread_mutex_unlock(&g_lock);
    return m;
}

EXPORT void ovr_FreeMessage(Message* m) { free(m); }
EXPORT uint32_t ovr_Message_GetType(const Message* m) { return m ? m->type : 0; }
EXPORT ovrRequest ovr_Message_GetRequestID(const Message* m) { return m ? m->id : 0; }
EXPORT bool ovr_Message_IsError(const Message* m) { return m && m->error; }
EXPORT void* ovr_Message_GetError(const Message* m) { return m && m->error ? g_error : NULL; }
EXPORT const char* ovr_Message_GetString(const Message* m) { return m && !m->error && m->text ? m->text : ""; }

EXPORT int ovr_Error_GetCode(const void* e) { return 1; }
EXPORT int ovr_Error_GetHttpCode(const void* e) { return 0; }
EXPORT const char* ovr_Error_GetMessage(const void* e) { return kNotAvailable; }

// a message's payload: the empty object, or NULL for an error reply (as Meta's SDK)
#define PAYLOAD(name) EXPORT void* name(const Message* m) { return m && !m->error ? g_empty : NULL; }
PAYLOAD(ovr_Message_GetDestinationArray)
PAYLOAD(ovr_Message_GetInvitePanelResultInfo)
PAYLOAD(ovr_Message_GetLaunchFriendRequestFlowResult)
PAYLOAD(ovr_Message_GetLaunchInvitePanelFlowResult)
PAYLOAD(ovr_Message_GetOrgScopedID)
PAYLOAD(ovr_Message_GetProductArray)
PAYLOAD(ovr_Message_GetPurchase)
PAYLOAD(ovr_Message_GetPurchaseArray)
PAYLOAD(ovr_Message_GetRoom)
PAYLOAD(ovr_Message_GetRoomInviteNotification)
PAYLOAD(ovr_Message_GetRoomInviteNotificationArray)
PAYLOAD(ovr_Message_GetUser)
PAYLOAD(ovr_Message_GetUserAndRoomArray)
PAYLOAD(ovr_Message_GetUserArray)
PAYLOAD(ovr_Message_GetUserProof)

// ---------------------------------------------------------------------------
// requests: each is answered on the next ovr_PopMessage
// ---------------------------------------------------------------------------
#define REQUEST(name, type, text) EXPORT ovrRequest name() { ONCE(#name); return Reply(type, false, text); }
#define UNAVAILABLE(name) EXPORT ovrRequest name() { ONCE(#name " -> not available"); return Reply(0, true, NULL); }

REQUEST(ovr_Entitlement_GetIsViewerEntitled, MESSAGE_ENTITLEMENT, NULL)
REQUEST(ovr_User_GetLoggedInUser, 0, NULL)
REQUEST(ovr_User_GetOrgScopedID, 0, NULL)
REQUEST(ovr_User_GetAccessToken, 0, "")
REQUEST(ovr_User_GetUserProof, 0, NULL)
REQUEST(ovr_User_GetLoggedInUserFriends, 0, NULL)
REQUEST(ovr_User_GetLoggedInUserRecentlyMetUsersAndRooms, 0, NULL)
REQUEST(ovr_User_GetNextUserArrayPage, 0, NULL)
REQUEST(ovr_User_GetNextUserAndRoomArrayPage, 0, NULL)
REQUEST(ovr_IAP_GetProductsBySKU, 0, NULL)
REQUEST(ovr_IAP_GetViewerPurchases, 0, NULL)
REQUEST(ovr_IAP_GetViewerPurchasesDurableCache, 0, NULL)
REQUEST(ovr_IAP_GetNextProductArrayPage, 0, NULL)
REQUEST(ovr_IAP_GetNextPurchaseArrayPage, 0, NULL)
REQUEST(ovr_Notification_GetRoomInvites, 0, NULL)
REQUEST(ovr_Notification_GetNextRoomInviteNotificationArrayPage, 0, NULL)
REQUEST(ovr_Notification_MarkAsRead, 0, NULL)
REQUEST(ovr_RichPresence_Set, 0, NULL)
REQUEST(ovr_RichPresence_Clear, 0, NULL)
REQUEST(ovr_RichPresence_GetDestinations, 0, NULL)
REQUEST(ovr_RichPresence_GetNextDestinationArrayPage, 0, NULL)
REQUEST(ovr_Room_Leave, 0, NULL)

UNAVAILABLE(ovr_Room_CreateAndJoinPrivate2)
UNAVAILABLE(ovr_Room_Get)
UNAVAILABLE(ovr_Room_GetInvitableUsers2)
UNAVAILABLE(ovr_Room_InviteUser)
UNAVAILABLE(ovr_Room_Join2)
UNAVAILABLE(ovr_Room_KickUser)
UNAVAILABLE(ovr_Room_LaunchInvitableUserFlow)
UNAVAILABLE(ovr_Room_UpdateDataStore)
UNAVAILABLE(ovr_Room_UpdateMembershipLockStatus)
UNAVAILABLE(ovr_Room_UpdateOwner)
UNAVAILABLE(ovr_Room_UpdatePrivateRoomJoinPolicy)
UNAVAILABLE(ovr_GroupPresence_LaunchInvitePanel)
UNAVAILABLE(ovr_GroupPresence_LaunchRosterPanel)
UNAVAILABLE(ovr_IAP_LaunchCheckoutFlow)
UNAVAILABLE(ovr_User_LaunchFriendRequestFlow)

// ---------------------------------------------------------------------------
// accessors on the empty object
// ---------------------------------------------------------------------------
#define EMPTY_ARRAY(T) \
    EXPORT size_t ovr_##T##_GetSize(const void* a) { return 0; } \
    EXPORT bool ovr_##T##_HasNextPage(const void* a) { return false; } \
    EXPORT void* ovr_##T##_GetElement(const void* a, size_t i) { return g_empty; }
EMPTY_ARRAY(DestinationArray)
EMPTY_ARRAY(ProductArray)
EMPTY_ARRAY(PurchaseArray)
EMPTY_ARRAY(RoomInviteNotificationArray)
EMPTY_ARRAY(UserAndRoomArray)
EMPTY_ARRAY(UserArray)

#define STRING(name) EXPORT const char* name() { return ""; }
STRING(ovr_DataStore_GetValue)
STRING(ovr_Destination_GetApiName)
STRING(ovr_Destination_GetDisplayName)
STRING(ovr_LaunchDetails_GetDeeplinkMessage)
STRING(ovr_LaunchDetails_GetDestinationApiName)
STRING(ovr_LaunchDetails_GetLaunchSource)
STRING(ovr_LaunchDetails_GetLobbySessionID)
STRING(ovr_Product_GetDescription)
STRING(ovr_Product_GetFormattedPrice)
STRING(ovr_Product_GetName)
STRING(ovr_Product_GetSKU)
STRING(ovr_Purchase_GetSKU)
STRING(ovr_User_GetInviteToken)
STRING(ovr_User_GetPresence)
STRING(ovr_User_GetPresenceDeeplinkMessage)

#define VALUE(type, name, v) EXPORT type name() { return v; }
VALUE(ovrID, ovr_User_GetID, kUserID)
VALUE(ovrID, ovr_OrgScopedID_GetID, kUserID)
VALUE(const char*, ovr_User_GetOculusID, kUserName)
VALUE(const char*, ovr_UserProof_GetNonce, g_nonce)
VALUE(ovrID, ovr_Room_GetID, 0)
VALUE(ovrID, ovr_LaunchDetails_GetRoomID, 0)
VALUE(ovrID, ovr_RoomInviteNotification_GetID, 0)
VALUE(ovrID, ovr_RoomInviteNotification_GetRoomID, 0)
VALUE(unsigned long long, ovr_RoomInviteNotification_GetSentTime, 0)
VALUE(int, ovr_LaunchDetails_GetLaunchType, 1)   // ovrLaunchType_Normal
VALUE(int, ovr_Room_GetJoinPolicy, 0)            // ovrRoom_JoinPolicyNone
VALUE(int, ovr_User_GetPresenceStatus, 0)        // ovrUserPresenceStatus_Unknown
VALUE(bool, ovr_Room_GetIsMembershipLocked, false)
VALUE(bool, ovr_InvitePanelResultInfo_GetInvitesSent, false)
VALUE(bool, ovr_LaunchFriendRequestFlowResult_GetDidCancel, true)
VALUE(bool, ovr_LaunchFriendRequestFlowResult_GetDidSendRequest, false)
VALUE(void*, ovr_ApplicationLifecycle_GetLaunchDetails, g_empty)
VALUE(void*, ovr_LaunchInvitePanelFlowResult_GetInvitedUsers, g_empty)
VALUE(void*, ovr_Room_GetDataStore, g_empty)
VALUE(void*, ovr_Room_GetOwner, g_empty)
VALUE(void*, ovr_Room_GetUsers, g_empty)
VALUE(void*, ovr_UserAndRoom_GetUser, g_empty)

// ---------------------------------------------------------------------------
// options handles (Echo creates, fills and destroys them)
// ---------------------------------------------------------------------------
#define OPTIONS(T) \
    EXPORT void* ovr_##T##_Create(void) { return calloc(1, 16); } \
    EXPORT void ovr_##T##_Destroy(void* h) { free(h); }
OPTIONS(InviteOptions)
OPTIONS(RichPresenceOptions)
OPTIONS(RoomOptions)
OPTIONS(RosterOptions)

#define IGNORE(name) EXPORT void name() {}
IGNORE(ovr_InviteOptions_AddSuggestedUser)
IGNORE(ovr_RosterOptions_AddSuggestedUser)
IGNORE(ovr_RoomOptions_SetOrdering)
IGNORE(ovr_RichPresenceOptions_SetApiName)
IGNORE(ovr_RichPresenceOptions_SetCurrentCapacity)
IGNORE(ovr_RichPresenceOptions_SetDeeplinkMessageOverride)
IGNORE(ovr_RichPresenceOptions_SetEndTime)
IGNORE(ovr_RichPresenceOptions_SetExtraContext)
IGNORE(ovr_RichPresenceOptions_SetIsJoinable)
IGNORE(ovr_RichPresenceOptions_SetLobbySessionId)
IGNORE(ovr_RichPresenceOptions_SetMatchSessionId)
IGNORE(ovr_RichPresenceOptions_SetMaxCapacity)
IGNORE(ovr_RichPresenceOptions_SetStartTime)

// ---------------------------------------------------------------------------
// microphone, VoIP and peer-to-peer packets: handles that produce no data
// ---------------------------------------------------------------------------
// The microphone is real: Echo's OVR provider reads 16-bit mono PCM at 48 kHz from
// ovr_Microphone_GetPCM and encodes and sends it itself (incoming voice never touches the
// Platform SDK: players were heard with the VoIP decoder below producing nothing). Captured
// with AAudio into a 250 ms ring buffer; when Echo falls behind, the oldest samples go.
#define MIC_RATE 48000
#define MIC_RING (MIC_RATE / 4)   // 250 ms: a slow reader gets recent sound, not sound a second old
typedef struct {
    AAudioStream* stream;
    pthread_mutex_t lock;
    int16_t ring[MIC_RING];
    size_t head, count;
    uint64_t captured, lastLog, dropped;   // dropped: overwritten or skipped before Echo read them
    uint64_t sent20, sent40;               // Opus frames handed to Echo (20 and 40 ms)
    int peakIn, peakOut;   // the microphone's peak, and the peak of what Echo gets
    double sumSq;
    float x1, x2, y1, y2;   // the high-pass filter's state (MicData)
} Mic;

// Low rumble ("like high winds") goes through a 100 Hz high-pass. Level: with whole Opus frames
// (ovr_Microphone_GetPCM) and SteamOS's input at 50 %, the Frame's microphone peaks at about
// -9 dBFS and the Quest 3's at -8, and players heard it a bit quiet: +6 dB, with a soft limiter
// above -6 dBFS so shouting rounds off instead of clipping (the earlier -6 dB was for a
// microphone that reached 0 dBFS, which an automatic gain had made worse). The input level, and
// what Echo is sent, are logged every 5 s.
#define MIC_SCALE 2.0f
#define MIC_KNEE 16384.0f   // -6 dBFS: above it, tanh towards full scale
static float SoftLimit(float y) {
    float a = fabsf(y);
    if (a <= MIC_KNEE) return y;
    float out = MIC_KNEE + (32767.0f - MIC_KNEE) * tanhf((a - MIC_KNEE) / (32767.0f - MIC_KNEE));
    return y < 0 ? -out : out;
}
// RBJ high-pass, f0 100 Hz, Q 0.7071, fs 48 kHz, normalised by a0
#define HP_B0 0.990787f
#define HP_B1 -1.981573f
#define HP_B2 0.990787f
#define HP_A1 -1.981489f
#define HP_A2 0.981658f
static aaudio_data_callback_result_t MicData(AAudioStream* s, void* user, void* data, int32_t frames) {
    Mic* m = user;
    const int16_t* in = data;
    double sum = 0;
    int peak = 0;
    pthread_mutex_lock(&m->lock);
    for (int32_t i = 0; i < frames; ++i) {
        int v = in[i] < 0 ? -in[i] : in[i];
        if (v > peak) peak = v;
        sum += (double)in[i] * in[i];
        // 2nd-order high-pass at 100 Hz (RBJ, Q 0.707, for 48 kHz): wind and breath rumble out
        float x = (float)in[i];
        float y = HP_B0 * x + HP_B1 * m->x1 + HP_B2 * m->x2 - HP_A1 * m->y1 - HP_A2 * m->y2;
        m->x2 = m->x1; m->x1 = x; m->y2 = m->y1; m->y1 = y;
        y = SoftLimit(y * MIC_SCALE);
        int o = (int)(y < 0 ? -y : y);
        if (o > m->peakOut) m->peakOut = o;
        m->ring[(m->head + m->count) % MIC_RING] = (int16_t)y;
        if (m->count < MIC_RING) m->count++;
        else { m->head = (m->head + 1) % MIC_RING; m->dropped++; }
    }
    m->captured += (uint64_t)frames;
    pthread_mutex_unlock(&m->lock);
    if (peak > m->peakIn) m->peakIn = peak;
    m->sumSq += sum;
    if (m->captured - m->lastLog >= 5 * MIC_RATE) {   // every 5 s of capture
        double n = (double)(m->captured - m->lastLog);
        LOG("Platform SDK: microphone level: peak %.1f dBFS, RMS %.1f dBFS; to Echo: peak %.1f dBFS; samples Echo didn't "
            "read in time: %llu of %.0f; Opus frames sent: %llu of 20 ms, %llu of 40 ms",
            20.0 * log10((m->peakIn > 0 ? m->peakIn : 1) / 32768.0), 10.0 * log10((m->sumSq > 0 ? m->sumSq : 1) / n / (32768.0 * 32768.0)),
            20.0 * log10((m->peakOut > 0 ? m->peakOut : 1) / 32768.0),
            (unsigned long long)m->dropped, n, (unsigned long long)m->sent20, (unsigned long long)m->sent40);
        m->lastLog = m->captured;
        m->peakIn = m->peakOut = 0;
        m->sumSq = 0;
        m->dropped = 0;
        m->sent20 = m->sent40 = 0;
    }
    return AAUDIO_CALLBACK_RESULT_CONTINUE;
}

static void MicError(AAudioStream* s, void* user, aaudio_result_t error) {
    LOG("Platform SDK: microphone stream error %d (%s)", error, AAudio_convertResultToText(error));
}

static void MicClose(Mic* m) {
    if (!m->stream) return;
    AAudioStream_requestStop(m->stream);
    AAudioStream_close(m->stream);
    m->stream = NULL;
    LOG("Platform SDK: microphone stopped after %llu samples", (unsigned long long)m->captured);
}

EXPORT void* ovr_Microphone_Create(void) {
    Mic* m = calloc(1, sizeof(Mic));
    pthread_mutex_init(&m->lock, NULL);
    LOG("Platform SDK: ovr_Microphone_Create (stand-in, AAudio capture)");
    return m;
}

EXPORT void ovr_Microphone_Start(void* h) {
    Mic* m = h;
    if (!m || m->stream) return;
    AAudioStreamBuilder* b = NULL;
    aaudio_result_t r = AAudio_createStreamBuilder(&b);
    if (r == AAUDIO_OK) {
        AAudioStreamBuilder_setDirection(b, AAUDIO_DIRECTION_INPUT);
        AAudioStreamBuilder_setSampleRate(b, MIC_RATE);
        AAudioStreamBuilder_setChannelCount(b, 1);
        AAudioStreamBuilder_setFormat(b, AAUDIO_FORMAT_PCM_I16);
        AAudioStreamBuilder_setSharingMode(b, AAUDIO_SHARING_MODE_SHARED);
        AAudioStreamBuilder_setDataCallback(b, MicData, m);
        AAudioStreamBuilder_setErrorCallback(b, MicError, m);
        r = AAudioStreamBuilder_openStream(b, &m->stream);
        AAudioStreamBuilder_delete(b);
    }
    if (r == AAUDIO_OK) r = AAudioStream_requestStart(m->stream);
    if (r != AAUDIO_OK) {
        LOG("Platform SDK: microphone didn't start: %d (%s)", r, AAudio_convertResultToText(r));
        if (m->stream) { AAudioStream_close(m->stream); m->stream = NULL; }
        return;
    }
    LOG("Platform SDK: microphone started: %d Hz, %d channel(s), format %d", AAudioStream_getSampleRate(m->stream),
        AAudioStream_getChannelCount(m->stream), AAudioStream_getFormat(m->stream));
}

EXPORT void ovr_Microphone_Stop(void* h) { if (h) MicClose(h); }

EXPORT void ovr_Microphone_Destroy(void* h) {
    Mic* m = h;
    if (!m) return;
    MicClose(m);
    pthread_mutex_destroy(&m->lock);
    free(m);
}

// Echo reads the microphone once per game update (CR15NetVoipBroadcasterCS::UpdateRecord: up to
// MicAvailable() samples) and hands what it got straight to opus_encode as the frame size
// (libpnsrad's VoipEncode; Opus at 48 kHz, 24 kbit/s, 256-byte packets). Opus only takes
// 2.5/5/10/20/40/60 ms frames, so any other count fails and that update sends nothing: returning
// whatever had built up (667 samples an update at 72 Hz, 1333 at 36) lost most of the voice. So
// Echo gets whole Opus frames only: 20 ms, or 40 ms when it has fallen behind (a slow frame; the
// Frame build lets it ask for up to 2880), and nothing until 20 ms is there. 60 ms isn't used:
// at 24 kbit/s its packets can outgrow Echo's 256 bytes. Sound older than MIC_LAG is dropped
// after a read, so a stall doesn't leave the voice running late.
#define MIC_LAG (MIC_RATE / 10)   // 100 ms
static const size_t kOpusFrames[] = { 1920, 960, 480, 240, 120 };
EXPORT size_t ovr_Microphone_GetPCM(void* h, int16_t* out, size_t n) {
    Mic* m = h;
    if (!m || !out) return 0;
    pthread_mutex_lock(&m->lock);
    size_t smallest = n >= 960 ? 960 : 120;   // 20 ms packets unless Echo asks for less
    size_t got = 0;
    for (size_t i = 0; i < sizeof kOpusFrames / sizeof kOpusFrames[0] && !got; ++i)
        if (kOpusFrames[i] <= n && kOpusFrames[i] <= m->count && kOpusFrames[i] >= smallest) got = kOpusFrames[i];
    for (size_t i = 0; i < got; ++i) out[i] = m->ring[(m->head + i) % MIC_RING];
    m->head = (m->head + got) % MIC_RING;
    m->count -= got;
    if (m->count > MIC_LAG) {   // running late: keep the newest 100 ms
        size_t skip = m->count - MIC_LAG;
        m->head = (m->head + skip) % MIC_RING;
        m->count = MIC_LAG;
        m->dropped += skip;
    }
    if (got == 1920) m->sent40++;
    else if (got) m->sent20++;
    pthread_mutex_unlock(&m->lock);
    return got;
}

EXPORT void* ovr_Voip_CreateEncoder(void) { ONCE("ovr_Voip_CreateEncoder"); return calloc(1, 16); }
EXPORT void* ovr_Voip_CreateDecoder(void) { return calloc(1, 16); }
EXPORT void ovr_Voip_DestroyEncoder(void* h) { free(h); }
EXPORT void ovr_Voip_DestroyDecoder(void* h) { free(h); }
EXPORT size_t ovr_Voip_GetOutputBufferMaxSize(void) { return 4800; }   // 100 ms at 48 kHz
EXPORT size_t ovr_Voip_GetPCM(ovrID sender, int16_t* out, size_t n) { return 0; }
EXPORT size_t ovr_Voip_GetPCMSize(ovrID sender) { return 0; }
EXPORT size_t ovr_VoipEncoder_GetCompressedData(void* h, uint8_t* out, size_t n) { return 0; }
EXPORT size_t ovr_VoipDecoder_GetDecodedPCM(void* h, float* out, size_t n) { return 0; }
IGNORE(ovr_VoipEncoder_AddPCM)
IGNORE(ovr_VoipDecoder_Decode)
IGNORE(ovr_Voip_Accept)
IGNORE(ovr_Voip_Start)
IGNORE(ovr_Voip_Stop)
IGNORE(ovr_Voip_SetMicrophoneMuted)

EXPORT void* ovr_Net_ReadPacket(void) { return NULL; }
EXPORT bool ovr_Net_SendPacket() { return false; }
EXPORT bool ovr_Net_SendPacketToCurrentRoom() { return false; }
EXPORT bool ovr_Net_AcceptForCurrentRoom(void) { return false; }
IGNORE(ovr_Net_CloseForCurrentRoom)
IGNORE(ovr_Packet_Free)
VALUE(const void*, ovr_Packet_GetBytes, NULL)
VALUE(size_t, ovr_Packet_GetSize, 0)
VALUE(ovrID, ovr_Packet_GetSenderID, 0)

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------
EXPORT bool ovrID_FromString(ovrID* out, const char* s) {
    if (!out || !s || !*s) return false;
    char* end;
    *out = strtoull(s, &end, 10);
    return *end == 0;
}

typedef struct {   // OVR_KeyValuePair.h
    const char* key_;
    int valueType_;
    const char* stringValue_;
    int intValue_;
    double doubleValue_;
} ovrKeyValuePair;

EXPORT ovrKeyValuePair ovrKeyValuePair_makeString(const char* key, const char* value) {
    ovrKeyValuePair kv = {key, 0 /* ovrKeyValuePairType_String */, value, 0, 0};
    return kv;
}

EXPORT const char* ovrPlatformInitializeResult_ToString(int v) { return v == 0 ? "SUCCESS" : "UNKNOWN"; }
EXPORT const char* ovrLaunchType_ToString(int v) {
    static const char* names[] = {"UNKNOWN", "NORMAL", "INVITE", "COORDINATED", "DEEPLINK"};
    return v >= 0 && v < 5 ? names[v] : "UNKNOWN";
}
EXPORT const char* ovrRoomJoinPolicy_ToString(int v) {
    static const char* names[] = {"NONE", "EVERYONE", "FRIENDS_OF_MEMBERS", "FRIENDS_OF_OWNER", "INVITED_USERS"};
    return v >= 0 && v < 5 ? names[v] : "UNKNOWN";
}
