// EchoQuestXR runtime -- libvrapi.so for Echo VR (Quest), implemented on OpenXR.
//
// Echo's engine (libr15.so) calls 35 VrApi functions; this file implements the 28 seen in
// play (docs/vrapi-calls.md), plus the shutdown ones. The rest of VrApi's 114 exports are
// stubs (unimplemented.c, generated by build.py) that log once and return 0.
//
//   VrApi                              OpenXR
//   Initialize                         loader init, xrCreateInstance, xrGetSystem
//   Get{Instance,Device}ExtensionsVulkan   xrGetVulkan{Instance,Device}ExtensionsKHR
//   CreateSystemVulkan                 xrCreateSession (Echo's VkInstance/VkDevice), spaces, actions
//   CreateTextureSwapChain3            xrCreateSwapchain (2D array = one layer per eye)
//   EnterVrMode / LeaveVrMode          xrBeginSession when READY / let the runtime stop it
//   WaitFrame / BeginFrame             xrWaitFrame / xrBeginFrame + acquire the swapchain image
//   GetPredictedTracking2              xrLocateViews + xrLocateSpace (head), cached per time
//   SubmitFrame2                       release the image, xrEndFrame with one projection layer
//   Get*Input*, SetHapticVibration...  actions on /interaction_profiles/oculus/touch_controller
//   PollEvent                          session state -> visibility/focus events
//
// Logs to logcat under EchoQuestXR. Properties, read at startup:
//   debug.echoquestxr.pose grip      controllers from the grip pose (default: aim, which matches VrApi)
//   debug.echoquestxr.flip 0         don't flip images (VrApi's are bottom-up; default: flip)
//   debug.echoquestxr.test red|probe|redprobe   display-path diagnostics
#define XR_USE_PLATFORM_ANDROID
#define XR_USE_GRAPHICS_API_VULKAN
#define XR_USE_TIMESPEC
#include <android/log.h>
#include <jni.h>
#include <sys/system_properties.h>
#include <time.h>
#include <unistd.h>
#include <vulkan/vulkan.h>
#include <openxr/openxr.h>
#include <openxr/openxr_platform.h>

#include <algorithm>
#include <cmath>
#include <cstring>
#include <deque>
#include <set>
#include <sstream>
#include <string>
#include <vector>

#include "vrapi_layouts.h"

#define TAG "EchoQuestXR"
#define LOG(...) __android_log_print(ANDROID_LOG_INFO, TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, TAG, __VA_ARGS__)
#define EXPORT extern "C" __attribute__((visibility("default")))

namespace {

// ---------------------------------------------------------------------------
// state
// ---------------------------------------------------------------------------
struct Swapchain {
    XrSwapchain handle = XR_NULL_HANDLE;
    std::vector<XrSwapchainImageVulkanKHR> images;
    // Echo always makes an image view on each image's foveation (fragment density) map:
    // NRadEngine::CVR::Resize ignores the result of GetTextureSwapChainBufferFoveationVulkan.
    std::vector<VkImage> fdm;
    std::vector<VkDeviceMemory> fdmMemory;
    uint32_t fdmWidth = 0, fdmHeight = 0;
    int32_t width = 0, height = 0, arraySize = 1;
    int32_t acquired = -1;   // image index acquired this frame, -1 = none
    int32_t echoLast = -1;   // the image Echo rendered last frame (it goes round-robin)
    uint64_t mismatches = 0;
};

struct ViewCache { double time = -1; XrView views[2]; };

struct Hand {
    XrPath path = XR_NULL_PATH;
    XrSpace grip = XR_NULL_HANDLE, aim = XR_NULL_HANDLE;
    // acceleration, which OpenXR doesn't report: from the change in velocity, smoothed
    double lastTime = 0;
    vr::Vector3f lastLinear{}, lastAngular{}, linearAccel{}, angularAccel{};
    double peakSpeed = 0;   // m/s since the last log line
};

struct State {
    JavaVM* vm = nullptr;
    jobject activity = nullptr;
    XrInstance instance = XR_NULL_HANDLE;
    XrSystemId system = XR_NULL_SYSTEM_ID;
    XrSession session = XR_NULL_HANDLE;
    XrSpace local = XR_NULL_HANDLE, view = XR_NULL_HANDLE;
    XrSessionState state = XR_SESSION_STATE_UNKNOWN;
    bool running = false;       // xrBeginSession done, not ended
    bool wantRunning = false;   // between EnterVrMode and LeaveVrMode
    bool focused = false;

    VkInstance vkInstance = VK_NULL_HANDLE;
    VkPhysicalDevice vkPhysical = VK_NULL_HANDLE;
    VkDevice vkDevice = VK_NULL_HANDLE;
    uint32_t queueFamily = 0, queueIndex = 0;

    std::vector<Swapchain*> swapchains;

    // frame loop
    XrFrameState frame{XR_TYPE_FRAME_STATE};
    bool waited = false, begun = false;
    uint64_t waitedIndex = 0;      // Echo's frame index for the last xrWaitFrame
    double waitedTime = 0;         // its predicted display time, seconds
    double period = 1.0 / 72;
    uint64_t submitted = 0;        // frames ended, for once-per-frame input sync
    ViewCache cache[16];
    int cacheNext = 0;

    std::deque<int32_t> events;
    uint8_t recenterCount = 0;

    // input
    XrActionSet actionSet = XR_NULL_HANDLE;
    XrAction trigger, triggerTouch, grip, stick, stickClick, stickTouch, thumbrest, primary, primaryTouch,
             secondary, secondaryTouch, menu, gripPose, aimPose, haptic;
    Hand hands[2];
    uint64_t syncedFrame = ~0ull;
    bool useAimPose = false;
    bool flipY = true;   // VrApi images are bottom-up; debug.echoquestxr.flip=0 turns this off

    // debug.echoquestxr.test=red: paint every submitted image red (display-path test)
    bool testRed = false;
    // debug.echoquestxr.test=probe: read back a few pixels at release time and log them
    bool testProbe = false;
    VkBuffer probeBuf = VK_NULL_HANDLE;
    VkDeviceMemory probeMem = VK_NULL_HANDLE;
    VkCommandPool cmdPool = VK_NULL_HANDLE;
    VkCommandBuffer cmd = VK_NULL_HANDLE;
    VkFence fence = VK_NULL_HANDLE;

    // extensions
    bool hasTimespec = false, hasRefreshRate = false;
    PFN_xrGetVulkanInstanceExtensionsKHR getInstanceExts = nullptr;
    PFN_xrGetVulkanDeviceExtensionsKHR getDeviceExts = nullptr;
    PFN_xrGetVulkanGraphicsDeviceKHR getGraphicsDevice = nullptr;
    PFN_xrGetVulkanGraphicsRequirementsKHR getGraphicsRequirements = nullptr;
    PFN_xrConvertTimespecTimeToTimeKHR timespecToTime = nullptr;
    PFN_xrConvertTimeToTimespecTimeKHR timeToTimespec = nullptr;
    PFN_xrEnumerateDisplayRefreshRatesFB enumerateRates = nullptr;
    PFN_xrGetDisplayRefreshRateFB getRate = nullptr;
    PFN_xrRequestDisplayRefreshRateFB requestRate = nullptr;
    std::vector<float> rates;
} g;

bool Ok(XrResult r, const char* what) {
    if (XR_SUCCEEDED(r)) return true;
    char name[XR_MAX_RESULT_STRING_SIZE] = "";
    if (g.instance) xrResultToString(g.instance, r, name);
    LOGE("%s failed: %d %s", what, (int)r, name);
    return false;
}

template <typename T>
void GetProc(const char* name, T* fn) {
    if (!Ok(xrGetInstanceProcAddr(g.instance, name, reinterpret_cast<PFN_xrVoidFunction*>(fn)), name)) *fn = nullptr;
}

// ---------------------------------------------------------------------------
// time: VrApi uses CLOCK_MONOTONIC seconds
// ---------------------------------------------------------------------------
double Now() {
    timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return ts.tv_sec + ts.tv_nsec * 1e-9;
}

XrTime ToXrTime(double seconds) {
    timespec ts;
    ts.tv_sec = (time_t)seconds;
    ts.tv_nsec = (long)((seconds - (double)ts.tv_sec) * 1e9);
    XrTime t = 0;
    if (g.timespecToTime && XR_SUCCEEDED(g.timespecToTime(g.instance, &ts, &t))) return t;
    return (XrTime)(seconds * 1e9);   // Android runtimes use CLOCK_MONOTONIC nanoseconds
}

double ToSeconds(XrTime t) {
    timespec ts;
    if (g.timeToTimespec && XR_SUCCEEDED(g.timeToTimespec(g.instance, t, &ts))) return ts.tv_sec + ts.tv_nsec * 1e-9;
    return t * 1e-9;
}

// ---------------------------------------------------------------------------
// math
// ---------------------------------------------------------------------------
vr::Posef ToVr(const XrPosef& p) {
    return { { p.orientation.x, p.orientation.y, p.orientation.z, p.orientation.w }, { p.position.x, p.position.y, p.position.z } };
}

// projection Echo expects: VrApi's, near plane 0.1, far at infinity (matches the recording)
vr::Matrix4f Projection(const XrFovf& fov) {
    const float nearZ = 0.1f;
    float l = std::tan(-fov.angleLeft), r = std::tan(fov.angleRight), u = std::tan(fov.angleUp), d = std::tan(-fov.angleDown);
    vr::Matrix4f m{};
    m.M[0][0] = 2 / (l + r);
    m.M[0][2] = (r - l) / (l + r);
    m.M[1][1] = 2 / (u + d);
    m.M[1][2] = (u - d) / (u + d);
    m.M[2][2] = -1;
    m.M[2][3] = -2 * nearZ;
    m.M[3][2] = -1;
    return m;
}

// world-to-eye: inverse of the eye's pose
vr::Matrix4f ViewMatrix(const XrPosef& p) {
    const XrQuaternionf& q = p.orientation;
    float xx = q.x * q.x, yy = q.y * q.y, zz = q.z * q.z, xy = q.x * q.y, xz = q.x * q.z, yz = q.y * q.z;
    float wx = q.w * q.x, wy = q.w * q.y, wz = q.w * q.z;
    float R[3][3] = { { 1 - 2 * (yy + zz), 2 * (xy - wz), 2 * (xz + wy) },
                      { 2 * (xy + wz), 1 - 2 * (xx + zz), 2 * (yz - wx) },
                      { 2 * (xz - wy), 2 * (yz + wx), 1 - 2 * (xx + yy) } };
    const float t[3] = { p.position.x, p.position.y, p.position.z };
    vr::Matrix4f m{};
    for (int i = 0; i < 3; ++i) {
        for (int j = 0; j < 3; ++j) m.M[i][j] = R[j][i];   // transpose
        m.M[i][3] = -(R[0][i] * t[0] + R[1][i] * t[1] + R[2][i] * t[2]);
    }
    m.M[3][3] = 1;
    return m;
}

uint32_t Status(XrSpaceLocationFlags f) {
    uint32_t s = vr::kHmdConnected;
    if (f & XR_SPACE_LOCATION_ORIENTATION_VALID_BIT) s |= vr::kOrientationValid;
    if (f & XR_SPACE_LOCATION_POSITION_VALID_BIT) s |= vr::kPositionValid;
    if (f & XR_SPACE_LOCATION_ORIENTATION_TRACKED_BIT) s |= vr::kOrientationTracked;
    if (f & XR_SPACE_LOCATION_POSITION_TRACKED_BIT) s |= vr::kPositionTracked;
    return s;
}

// locates `space` in LOCAL at `seconds`, with velocities; false if nothing valid
bool Locate(XrSpace space, double seconds, vr::RigidBodyPosef& out, uint32_t& status) {
    out = {};
    out.Pose.Orientation.w = 1;
    out.TimeInSeconds = seconds;
    out.PredictionInSeconds = std::max(0.0, seconds - Now());
    status = 0;
    if (!g.session || space == XR_NULL_HANDLE) return false;
    XrSpaceVelocity vel{XR_TYPE_SPACE_VELOCITY};
    XrSpaceLocation loc{XR_TYPE_SPACE_LOCATION, &vel};
    if (XR_FAILED(xrLocateSpace(space, g.local, ToXrTime(seconds), &loc))) return false;
    if (!(loc.locationFlags & XR_SPACE_LOCATION_ORIENTATION_VALID_BIT)) return false;
    out.Pose = ToVr(loc.pose);
    if (vel.velocityFlags & XR_SPACE_VELOCITY_ANGULAR_VALID_BIT)
        out.AngularVelocity = { vel.angularVelocity.x, vel.angularVelocity.y, vel.angularVelocity.z };
    if (vel.velocityFlags & XR_SPACE_VELOCITY_LINEAR_VALID_BIT)
        out.LinearVelocity = { vel.linearVelocity.x, vel.linearVelocity.y, vel.linearVelocity.z };
    status = Status(loc.locationFlags);
    return true;
}

// ---------------------------------------------------------------------------
// session
// ---------------------------------------------------------------------------
void BeginSessionIfReady() {
    if (g.running || !g.wantRunning || g.state != XR_SESSION_STATE_READY) return;
    XrSessionBeginInfo bi{XR_TYPE_SESSION_BEGIN_INFO};
    bi.primaryViewConfigurationType = XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO;
    if (Ok(xrBeginSession(g.session, &bi), "xrBeginSession")) {
        g.running = true;
        LOG("session running");
    }
}

void OnSessionState(XrSessionState s) {
    XrSessionState old = g.state;
    g.state = s;
    LOG("session state %d -> %d", (int)old, (int)s);
    switch (s) {
    case XR_SESSION_STATE_READY: BeginSessionIfReady(); break;
    case XR_SESSION_STATE_SYNCHRONIZED:
        if (old == XR_SESSION_STATE_VISIBLE) g.events.push_back(vr::kEventVisibilityLost);
        break;
    case XR_SESSION_STATE_VISIBLE:
        if (old == XR_SESSION_STATE_FOCUSED) { g.focused = false; g.events.push_back(vr::kEventFocusLost); }
        else g.events.push_back(vr::kEventVisibilityGained);
        break;
    case XR_SESSION_STATE_FOCUSED:
        g.focused = true;
        g.events.push_back(vr::kEventFocusGained);
        break;
    case XR_SESSION_STATE_STOPPING:
        if (g.begun) LOGE("session stopping mid-frame");
        Ok(xrEndSession(g.session), "xrEndSession");
        g.running = g.waited = g.begun = false;
        break;
    case XR_SESSION_STATE_EXITING:
    case XR_SESSION_STATE_LOSS_PENDING:
        LOGE("session is exiting (state %d)", (int)s);
        break;
    default: break;
    }
}

void PumpEvents() {
    if (!g.instance) return;
    XrEventDataBuffer ev{XR_TYPE_EVENT_DATA_BUFFER};
    while (xrPollEvent(g.instance, &ev) == XR_SUCCESS) {
        switch (ev.type) {
        case XR_TYPE_EVENT_DATA_SESSION_STATE_CHANGED:
            OnSessionState(reinterpret_cast<XrEventDataSessionStateChanged*>(&ev)->state);
            break;
        case XR_TYPE_EVENT_DATA_REFERENCE_SPACE_CHANGE_PENDING:
            ++g.recenterCount;   // Echo watches the controllers' recenter count
            LOG("reference space changed (recenter)");
            break;
        case XR_TYPE_EVENT_DATA_INSTANCE_LOSS_PENDING: LOGE("instance loss pending"); break;
        case XR_TYPE_EVENT_DATA_INTERACTION_PROFILE_CHANGED: LOG("interaction profile changed"); break;
        default: break;
        }
        ev = { XR_TYPE_EVENT_DATA_BUFFER };
    }
}

XrAction MakeAction(const char* name, XrActionType type, bool perHand = true) {
    XrActionCreateInfo ci{XR_TYPE_ACTION_CREATE_INFO};
    strncpy(ci.actionName, name, sizeof(ci.actionName) - 1);
    strncpy(ci.localizedActionName, name, sizeof(ci.localizedActionName) - 1);
    ci.actionType = type;
    XrPath subs[2] = { g.hands[0].path, g.hands[1].path };
    if (perHand) { ci.countSubactionPaths = 2; ci.subactionPaths = subs; }
    XrAction a = XR_NULL_HANDLE;
    Ok(xrCreateAction(g.actionSet, &ci, &a), name);
    return a;
}

XrPath Path(const char* s) {
    XrPath p = XR_NULL_PATH;
    Ok(xrStringToPath(g.instance, s, &p), s);
    return p;
}

void CreateInput() {
    g.hands[0].path = Path("/user/hand/left");
    g.hands[1].path = Path("/user/hand/right");
    XrActionSetCreateInfo si{XR_TYPE_ACTION_SET_CREATE_INFO};
    strcpy(si.actionSetName, "echo");
    strcpy(si.localizedActionSetName, "Echo VR");
    if (!Ok(xrCreateActionSet(g.instance, &si, &g.actionSet), "xrCreateActionSet")) return;
    g.trigger = MakeAction("trigger", XR_ACTION_TYPE_FLOAT_INPUT);
    g.triggerTouch = MakeAction("trigger_touch", XR_ACTION_TYPE_BOOLEAN_INPUT);
    g.grip = MakeAction("grip", XR_ACTION_TYPE_FLOAT_INPUT);
    g.stick = MakeAction("thumbstick", XR_ACTION_TYPE_VECTOR2F_INPUT);
    g.stickClick = MakeAction("thumbstick_click", XR_ACTION_TYPE_BOOLEAN_INPUT);
    g.stickTouch = MakeAction("thumbstick_touch", XR_ACTION_TYPE_BOOLEAN_INPUT);
    g.thumbrest = MakeAction("thumbrest_touch", XR_ACTION_TYPE_BOOLEAN_INPUT);
    g.primary = MakeAction("primary_button", XR_ACTION_TYPE_BOOLEAN_INPUT);         // X / A
    g.primaryTouch = MakeAction("primary_touch", XR_ACTION_TYPE_BOOLEAN_INPUT);
    g.secondary = MakeAction("secondary_button", XR_ACTION_TYPE_BOOLEAN_INPUT);     // Y / B
    g.secondaryTouch = MakeAction("secondary_touch", XR_ACTION_TYPE_BOOLEAN_INPUT);
    g.menu = MakeAction("menu", XR_ACTION_TYPE_BOOLEAN_INPUT);
    g.gripPose = MakeAction("grip_pose", XR_ACTION_TYPE_POSE_INPUT);
    g.aimPose = MakeAction("aim_pose", XR_ACTION_TYPE_POSE_INPUT);
    g.haptic = MakeAction("haptic", XR_ACTION_TYPE_VIBRATION_OUTPUT);

    std::vector<XrActionSuggestedBinding> b;
    auto bind = [&](XrAction a, const char* left, const char* right) {
        if (left) b.push_back({ a, Path((std::string("/user/hand/left/") + left).c_str()) });
        if (right) b.push_back({ a, Path((std::string("/user/hand/right/") + right).c_str()) });
    };
    bind(g.trigger, "input/trigger/value", "input/trigger/value");
    bind(g.triggerTouch, "input/trigger/touch", "input/trigger/touch");
    bind(g.grip, "input/squeeze/value", "input/squeeze/value");
    bind(g.stick, "input/thumbstick", "input/thumbstick");
    bind(g.stickClick, "input/thumbstick/click", "input/thumbstick/click");
    bind(g.stickTouch, "input/thumbstick/touch", "input/thumbstick/touch");
    bind(g.thumbrest, "input/thumbrest/touch", "input/thumbrest/touch");
    bind(g.primary, "input/x/click", "input/a/click");
    bind(g.primaryTouch, "input/x/touch", "input/a/touch");
    bind(g.secondary, "input/y/click", "input/b/click");
    bind(g.secondaryTouch, "input/y/touch", "input/b/touch");
    bind(g.menu, "input/menu/click", nullptr);
    bind(g.gripPose, "input/grip/pose", "input/grip/pose");
    bind(g.aimPose, "input/aim/pose", "input/aim/pose");
    bind(g.haptic, "output/haptic", "output/haptic");
    XrInteractionProfileSuggestedBinding sb{XR_TYPE_INTERACTION_PROFILE_SUGGESTED_BINDING};
    sb.interactionProfile = Path("/interaction_profiles/oculus/touch_controller");
    sb.countSuggestedBindings = (uint32_t)b.size();
    sb.suggestedBindings = b.data();
    Ok(xrSuggestInteractionProfileBindings(g.instance, &sb), "xrSuggestInteractionProfileBindings");

    XrSessionActionSetsAttachInfo ai{XR_TYPE_SESSION_ACTION_SETS_ATTACH_INFO};
    ai.countActionSets = 1;
    ai.actionSets = &g.actionSet;
    Ok(xrAttachSessionActionSets(g.session, &ai), "xrAttachSessionActionSets");
    for (Hand& h : g.hands) {
        XrActionSpaceCreateInfo ci{XR_TYPE_ACTION_SPACE_CREATE_INFO};
        ci.subactionPath = h.path;
        ci.poseInActionSpace.orientation.w = 1;
        ci.action = g.gripPose;
        Ok(xrCreateActionSpace(g.session, &ci, &h.grip), "grip space");
        ci.action = g.aimPose;
        Ok(xrCreateActionSpace(g.session, &ci, &h.aim), "aim space");
    }
}

bool CreateSession() {
    XrGraphicsBindingVulkanKHR binding{XR_TYPE_GRAPHICS_BINDING_VULKAN_KHR};
    binding.instance = g.vkInstance;
    binding.physicalDevice = g.vkPhysical;
    binding.device = g.vkDevice;
    binding.queueFamilyIndex = g.queueFamily;
    binding.queueIndex = g.queueIndex;
    XrSessionCreateInfo ci{XR_TYPE_SESSION_CREATE_INFO, &binding};
    ci.systemId = g.system;
    if (!Ok(xrCreateSession(g.instance, &ci, &g.session), "xrCreateSession")) return false;
    XrReferenceSpaceCreateInfo rs{XR_TYPE_REFERENCE_SPACE_CREATE_INFO};
    rs.poseInReferenceSpace.orientation.w = 1;
    rs.referenceSpaceType = XR_REFERENCE_SPACE_TYPE_LOCAL;   // VrApi's default tracking space (eye level)
    Ok(xrCreateReferenceSpace(g.session, &rs, &g.local), "LOCAL space");
    rs.referenceSpaceType = XR_REFERENCE_SPACE_TYPE_VIEW;
    Ok(xrCreateReferenceSpace(g.session, &rs, &g.view), "VIEW space");
    CreateInput();
    LOG("session created (queue family %u, index %u)", g.queueFamily, g.queueIndex);
    return true;
}

// "a b c" + "c d" -> "a b c d"
std::string MergeExtensions(const char* vrapiList, const std::string& runtimeList) {
    std::vector<std::string> out;
    std::set<std::string> seen;
    for (const std::string& list : { std::string(vrapiList), runtimeList }) {
        std::istringstream in(list);
        std::string e;
        while (in >> e)
            if (seen.insert(e).second) out.push_back(e);
    }
    std::string s;
    for (const std::string& e : out) s += (s.empty() ? "" : " ") + e;
    return s;
}

int32_t WriteExtensions(const std::string& list, char* names, uint32_t* size) {
    if (!size) return vr::kErrorInvalidParameter;
    uint32_t need = (uint32_t)list.size() + 1, cap = *size;
    if (!names) { *size = need; return vr::kSuccess; }
    if (cap == 0 || cap > 65536) cap = 4096;   // Echo passes a buffer without saying how big
    if (need > cap) { LOGE("extension list (%u bytes) doesn't fit in %u", need, cap); return vr::kErrorInvalidParameter; }
    memcpy(names, list.c_str(), need);
    *size = need;
    return vr::kSuccess;
}

// One foveation map per swapchain image: R8G8_UNORM (the format Echo views it as), a
// 2-layer array like the eye buffers, one texel per 16x16 pixels (the Quest 3's density
// texel size). Echo only needs a valid image to make its view; nothing reads it yet.
void FillFoveationMaps(Swapchain* s);
void CreateFoveationMaps(Swapchain* s) {
    s->fdmWidth = (uint32_t)(s->width + 15) / 16;
    s->fdmHeight = (uint32_t)(s->height + 15) / 16;
    VkPhysicalDeviceMemoryProperties mem;
    vkGetPhysicalDeviceMemoryProperties(g.vkPhysical, &mem);
    for (size_t i = 0; i < s->images.size(); ++i) {
        VkImageCreateInfo ci{VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO};
        ci.imageType = VK_IMAGE_TYPE_2D;
        ci.format = VK_FORMAT_R8G8_UNORM;
        ci.extent = { s->fdmWidth, s->fdmHeight, 1 };
        ci.mipLevels = 1;
        ci.arrayLayers = (uint32_t)s->arraySize;
        ci.samples = VK_SAMPLE_COUNT_1_BIT;
        ci.tiling = VK_IMAGE_TILING_OPTIMAL;
        ci.usage = VK_IMAGE_USAGE_FRAGMENT_DENSITY_MAP_BIT_EXT | VK_IMAGE_USAGE_SAMPLED_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT;
        ci.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
        VkImage img = VK_NULL_HANDLE;
        VkDeviceMemory m = VK_NULL_HANDLE;
        if (vkCreateImage(g.vkDevice, &ci, nullptr, &img) == VK_SUCCESS) {
            VkMemoryRequirements req;
            vkGetImageMemoryRequirements(g.vkDevice, img, &req);
            VkMemoryAllocateInfo ai{VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO};
            ai.allocationSize = req.size;
            for (uint32_t t = 0; t < mem.memoryTypeCount; ++t)
                if ((req.memoryTypeBits & (1u << t)) && (mem.memoryTypes[t].propertyFlags & VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT)) {
                    ai.memoryTypeIndex = t;
                    break;
                }
            if (vkAllocateMemory(g.vkDevice, &ai, nullptr, &m) != VK_SUCCESS || vkBindImageMemory(g.vkDevice, img, m, 0) != VK_SUCCESS) {
                LOGE("foveation map %zu: no memory", i);
                vkDestroyImage(g.vkDevice, img, nullptr);
                if (m) vkFreeMemory(g.vkDevice, m, nullptr);
                img = VK_NULL_HANDLE;
                m = VK_NULL_HANDLE;
            }
        } else {
            LOGE("foveation map %zu: vkCreateImage failed", i);
        }
        s->fdm.push_back(img);
        s->fdmMemory.push_back(m);
    }
    FillFoveationMaps(s);
    LOG("foveation maps: %zu x %ux%u x%d, full density", s->fdm.size(), s->fdmWidth, s->fdmHeight, s->arraySize);
}

void EnsureCommands();
void SubmitAndWait();
void Barrier(VkImage img, uint32_t layers, VkImageLayout from, VkImageLayout to, VkAccessFlags src, VkAccessFlags dst);

// 255 = full resolution everywhere, the same as foveation level 0
void FillFoveationMaps(Swapchain* s) {
    EnsureCommands();
    VkCommandBufferBeginInfo bi{VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};
    bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
    vkResetCommandBuffer(g.cmd, 0);
    vkBeginCommandBuffer(g.cmd, &bi);
    VkClearColorValue full{};
    full.float32[0] = full.float32[1] = 1;
    VkImageSubresourceRange range{ VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, (uint32_t)s->arraySize };
    for (VkImage img : s->fdm) {
        if (!img) continue;
        Barrier(img, (uint32_t)s->arraySize, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 0, VK_ACCESS_TRANSFER_WRITE_BIT);
        vkCmdClearColorImage(g.cmd, img, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, &full, 1, &range);
        Barrier(img, (uint32_t)s->arraySize, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, VK_IMAGE_LAYOUT_FRAGMENT_DENSITY_MAP_OPTIMAL_EXT,
                VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_FRAGMENT_DENSITY_MAP_READ_BIT_EXT);
    }
    vkEndCommandBuffer(g.cmd);
    SubmitAndWait();
}

void DestroyFoveationMaps(Swapchain* s) {
    for (VkImage i : s->fdm) if (i) vkDestroyImage(g.vkDevice, i, nullptr);
    for (VkDeviceMemory m : s->fdmMemory) if (m) vkFreeMemory(g.vkDevice, m, nullptr);
    s->fdm.clear();
    s->fdmMemory.clear();
}

void EnsureCommands() {
    if (!g.cmdPool) {
        VkCommandPoolCreateInfo pi{VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO};
        pi.flags = VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;
        pi.queueFamilyIndex = g.queueFamily;
        vkCreateCommandPool(g.vkDevice, &pi, nullptr, &g.cmdPool);
        VkCommandBufferAllocateInfo ai{VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO};
        ai.commandPool = g.cmdPool;
        ai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
        ai.commandBufferCount = 1;
        vkAllocateCommandBuffers(g.vkDevice, &ai, &g.cmd);
        VkFenceCreateInfo fi{VK_STRUCTURE_TYPE_FENCE_CREATE_INFO};
        vkCreateFence(g.vkDevice, &fi, nullptr, &g.fence);
    }
}

void SubmitAndWait() {
    VkQueue q = VK_NULL_HANDLE;
    vkGetDeviceQueue(g.vkDevice, g.queueFamily, g.queueIndex, &q);
    VkSubmitInfo si{VK_STRUCTURE_TYPE_SUBMIT_INFO};
    si.commandBufferCount = 1;
    si.pCommandBuffers = &g.cmd;
    vkResetFences(g.vkDevice, 1, &g.fence);
    if (vkQueueSubmit(q, 1, &si, g.fence) == VK_SUCCESS) vkWaitForFences(g.vkDevice, 1, &g.fence, VK_TRUE, 100000000);
}

void Barrier(VkImage img, uint32_t layers, VkImageLayout from, VkImageLayout to, VkAccessFlags src, VkAccessFlags dst) {
    VkImageMemoryBarrier b{VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER};
    b.srcAccessMask = src;
    b.dstAccessMask = dst;
    b.oldLayout = from;
    b.newLayout = to;
    b.srcQueueFamilyIndex = b.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    b.image = img;
    b.subresourceRange = { VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, layers };
    vkCmdPipelineBarrier(g.cmd, VK_PIPELINE_STAGE_ALL_COMMANDS_BIT, VK_PIPELINE_STAGE_ALL_COMMANDS_BIT, 0, 0, nullptr, 0, nullptr, 1, &b);
}

// Test: copies 5 pixels (centre and four points around it, eye 0) to a host buffer and logs
// them. Assumes Echo left the image in COLOR_ATTACHMENT_OPTIMAL and puts it back there.
void ProbeImage(Swapchain* s, int32_t index);
void Probe(Swapchain* s) {   // all images: the acquired one, and the ones from earlier frames
    if (s->acquired < 0) return;
    for (int32_t i = 0; i < (int32_t)s->images.size(); ++i) ProbeImage(s, i);
}
void ProbeImage(Swapchain* s, int32_t index) {
    EnsureCommands();
    if (!g.probeBuf) {
        VkBufferCreateInfo bi{VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO};
        bi.size = 64;
        bi.usage = VK_BUFFER_USAGE_TRANSFER_DST_BIT;
        vkCreateBuffer(g.vkDevice, &bi, nullptr, &g.probeBuf);
        VkMemoryRequirements req;
        vkGetBufferMemoryRequirements(g.vkDevice, g.probeBuf, &req);
        VkPhysicalDeviceMemoryProperties mem;
        vkGetPhysicalDeviceMemoryProperties(g.vkPhysical, &mem);
        VkMemoryAllocateInfo ai{VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO};
        ai.allocationSize = req.size;
        for (uint32_t t = 0; t < mem.memoryTypeCount; ++t)
            if ((req.memoryTypeBits & (1u << t)) && (mem.memoryTypes[t].propertyFlags &
                (VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT)) ==
                (VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT)) { ai.memoryTypeIndex = t; break; }
        vkAllocateMemory(g.vkDevice, &ai, nullptr, &g.probeMem);
        vkBindBufferMemory(g.vkDevice, g.probeBuf, g.probeMem, 0);
    }
    VkImage img = s->images[index].image;
    VkCommandBufferBeginInfo bi{VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};
    bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
    vkResetCommandBuffer(g.cmd, 0);
    vkBeginCommandBuffer(g.cmd, &bi);
    Barrier(img, (uint32_t)s->arraySize, VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
            VK_ACCESS_MEMORY_WRITE_BIT, VK_ACCESS_TRANSFER_READ_BIT);
    const int32_t pts[5][2] = { { s->width / 2, s->height / 2 }, { s->width / 4, s->height / 2 }, { 3 * s->width / 4, s->height / 2 },
                                { s->width / 2, s->height / 4 }, { s->width / 2, 3 * s->height / 4 } };
    for (int i = 0; i < 5; ++i) {
        VkBufferImageCopy c{};
        c.bufferOffset = (VkDeviceSize)i * 4;
        c.imageSubresource = { VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1 };
        c.imageOffset = { pts[i][0], pts[i][1], 0 };
        c.imageExtent = { 1, 1, 1 };
        vkCmdCopyImageToBuffer(g.cmd, img, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, g.probeBuf, 1, &c);
    }
    Barrier(img, (uint32_t)s->arraySize, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
            VK_ACCESS_TRANSFER_READ_BIT, VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT);
    vkEndCommandBuffer(g.cmd);
    SubmitAndWait();
    uint8_t* p = nullptr;
    if (vkMapMemory(g.vkDevice, g.probeMem, 0, 64, 0, (void**)&p) == VK_SUCCESS) {
        LOG("probe image %d%s: centre %02x%02x%02x%02x  left %02x%02x%02x%02x  right %02x%02x%02x%02x  up %02x%02x%02x%02x  down %02x%02x%02x%02x",
            index, index == s->acquired ? " (this frame)" : "", p[0], p[1], p[2], p[3], p[4], p[5], p[6], p[7], p[8], p[9], p[10], p[11], p[12], p[13], p[14], p[15],
            p[16], p[17], p[18], p[19]);
        vkUnmapMemory(g.vkDevice, g.probeMem);
    }
}

// Test: clear the acquired image of `s` to red on Echo's queue, leaving it in
// COLOR_ATTACHMENT_OPTIMAL as OpenXR expects at release.
void PaintRed(Swapchain* s) {
    if (s->acquired < 0) return;
    EnsureCommands();
    VkImage img = s->images[s->acquired].image;
    VkImageSubresourceRange range{ VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, (uint32_t)s->arraySize };
    VkCommandBufferBeginInfo bi{VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};
    bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
    vkResetCommandBuffer(g.cmd, 0);
    vkBeginCommandBuffer(g.cmd, &bi);
    VkImageMemoryBarrier b{VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER};
    b.srcAccessMask = VK_ACCESS_MEMORY_WRITE_BIT;
    b.dstAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
    b.oldLayout = VK_IMAGE_LAYOUT_UNDEFINED;
    b.newLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
    b.srcQueueFamilyIndex = b.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    b.image = img;
    b.subresourceRange = range;
    vkCmdPipelineBarrier(g.cmd, VK_PIPELINE_STAGE_ALL_COMMANDS_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT, 0, 0, nullptr, 0, nullptr, 1, &b);
    VkClearColorValue red{};
    red.float32[0] = 1;
    red.float32[3] = 1;
    vkCmdClearColorImage(g.cmd, img, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, &red, 1, &range);
    b.srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
    b.dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT | VK_ACCESS_SHADER_READ_BIT;
    b.oldLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
    b.newLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
    vkCmdPipelineBarrier(g.cmd, VK_PIPELINE_STAGE_TRANSFER_BIT, VK_PIPELINE_STAGE_ALL_COMMANDS_BIT, 0, 0, nullptr, 0, nullptr, 1, &b);
    vkEndCommandBuffer(g.cmd);
    SubmitAndWait();
}

Swapchain* FindSwapchain(const void* p) {
    for (Swapchain* s : g.swapchains)
        if (s == p) return s;
    return nullptr;
}

const ViewCache* FindViews(double time) {
    const ViewCache* best = nullptr;
    for (const ViewCache& c : g.cache)
        if (c.time >= 0 && (!best || std::fabs(c.time - time) < std::fabs(best->time - time))) best = &c;
    return best;
}

// once per frame, before the first input read
void SyncInput() {
    if (g.syncedFrame == g.submitted || !g.session || !g.focused) return;
    g.syncedFrame = g.submitted;
    XrActiveActionSet active{ g.actionSet, XR_NULL_PATH };
    XrActionsSyncInfo si{XR_TYPE_ACTIONS_SYNC_INFO};
    si.countActiveActionSets = 1;
    si.activeActionSets = &active;
    xrSyncActions(g.session, &si);
}

bool Bool(XrAction a, int hand) {
    XrActionStateGetInfo gi{XR_TYPE_ACTION_STATE_GET_INFO};
    gi.action = a;
    gi.subactionPath = g.hands[hand].path;
    XrActionStateBoolean s{XR_TYPE_ACTION_STATE_BOOLEAN};
    return XR_SUCCEEDED(xrGetActionStateBoolean(g.session, &gi, &s)) && s.isActive && s.currentState;
}

float Float(XrAction a, int hand) {
    XrActionStateGetInfo gi{XR_TYPE_ACTION_STATE_GET_INFO};
    gi.action = a;
    gi.subactionPath = g.hands[hand].path;
    XrActionStateFloat s{XR_TYPE_ACTION_STATE_FLOAT};
    return XR_SUCCEEDED(xrGetActionStateFloat(g.session, &gi, &s)) && s.isActive ? s.currentState : 0.f;
}

XrVector2f Vec2(XrAction a, int hand) {
    XrActionStateGetInfo gi{XR_TYPE_ACTION_STATE_GET_INFO};
    gi.action = a;
    gi.subactionPath = g.hands[hand].path;
    XrActionStateVector2f s{XR_TYPE_ACTION_STATE_VECTOR2F};
    return XR_SUCCEEDED(xrGetActionStateVector2f(g.session, &gi, &s)) && s.isActive ? s.currentState : XrVector2f{ 0, 0 };
}

int HandOf(uint32_t deviceID) {
    return deviceID == vr::kDeviceLeft ? 0 : deviceID == vr::kDeviceRight ? 1 : -1;
}

// what the Quest 3's VrApi reported for the two Touch controllers (bytes 8-47)
const uint8_t kCapabilities[2][40] = {
    { 0xc7, 0x66, 0x01, 0x00, 0x00, 0x07, 0x10, 0xa4, 0xff, 0xff, 0xff, 0xff, 0, 0, 0, 0, 0, 0, 0, 0,
      0x19, 0, 0, 0, 0x02, 0, 0, 0, 0x6c, 0x37, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0xcb, 0x66, 0x01, 0x00, 0x07, 0x00, 0x00, 0xa5, 0xff, 0xff, 0xff, 0xff, 0, 0, 0, 0, 0, 0, 0, 0,
      0x19, 0, 0, 0, 0x02, 0, 0, 0, 0x63, 0x5b, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
};

}  // namespace

// ===========================================================================
// VrApi
// ===========================================================================
EXPORT int32_t vrapi_Initialize(const vr::InitParms* p) {
    if (g.instance) return vr::kSuccess;
    if (!p || !p->java.Vm) return -1;
    char pose[PROP_VALUE_MAX] = "";
    __system_property_get("debug.echoquestxr.pose", pose);
    g.useAimPose = strcmp(pose, "grip") != 0;   // aim matches VrApi's controller pose (tested on Quest 3)
    char flip[PROP_VALUE_MAX] = "";
    __system_property_get("debug.echoquestxr.flip", flip);
    g.flipY = strcmp(flip, "0") != 0;
    char test[PROP_VALUE_MAX] = "";
    __system_property_get("debug.echoquestxr.test", test);
    g.testRed = !strcmp(test, "red") || !strcmp(test, "redprobe");
    g.testProbe = !strcmp(test, "probe") || !strcmp(test, "redprobe");
    if (g.testRed) LOG("TEST MODE: every submitted image is painted red");
    if (g.testProbe) LOG("TEST MODE: probing submitted pixels once a second");
    LOG("EchoQuestXR: VrApi %d.%d.%d on OpenXR (controller pose: %s, flip: %s)", p->MajorVersion, p->MinorVersion,
        p->PatchVersion, g.useAimPose ? "aim" : "grip", g.flipY ? "on" : "off");

    g.vm = p->java.Vm;
    JNIEnv* env = nullptr;
    g.vm->AttachCurrentThread(&env, nullptr);
    g.activity = env->NewGlobalRef(p->java.ActivityObject);

    PFN_xrInitializeLoaderKHR initLoader = nullptr;
    xrGetInstanceProcAddr(XR_NULL_HANDLE, "xrInitializeLoaderKHR", reinterpret_cast<PFN_xrVoidFunction*>(&initLoader));
    if (initLoader) {
        XrLoaderInitInfoAndroidKHR li{XR_TYPE_LOADER_INIT_INFO_ANDROID_KHR};
        li.applicationVM = g.vm;
        li.applicationContext = g.activity;
        Ok(initLoader(reinterpret_cast<XrLoaderInitInfoBaseHeaderKHR*>(&li)), "xrInitializeLoaderKHR");
    }

    uint32_t n = 0;
    xrEnumerateInstanceExtensionProperties(nullptr, 0, &n, nullptr);
    std::vector<XrExtensionProperties> props(n, { XR_TYPE_EXTENSION_PROPERTIES });
    xrEnumerateInstanceExtensionProperties(nullptr, n, &n, props.data());
    auto has = [&](const char* name) {
        for (auto& e : props) if (!strcmp(e.extensionName, name)) return true;
        return false;
    };
    std::vector<const char*> exts = { XR_KHR_ANDROID_CREATE_INSTANCE_EXTENSION_NAME, XR_KHR_VULKAN_ENABLE_EXTENSION_NAME };
    if ((g.hasTimespec = has(XR_KHR_CONVERT_TIMESPEC_TIME_EXTENSION_NAME))) exts.push_back(XR_KHR_CONVERT_TIMESPEC_TIME_EXTENSION_NAME);
    if ((g.hasRefreshRate = has(XR_FB_DISPLAY_REFRESH_RATE_EXTENSION_NAME))) exts.push_back(XR_FB_DISPLAY_REFRESH_RATE_EXTENSION_NAME);
    if (!has(XR_KHR_VULKAN_ENABLE_EXTENSION_NAME)) { LOGE("runtime has no XR_KHR_vulkan_enable"); return -1; }

    XrInstanceCreateInfoAndroidKHR android{XR_TYPE_INSTANCE_CREATE_INFO_ANDROID_KHR};
    android.applicationVM = g.vm;
    android.applicationActivity = g.activity;
    XrInstanceCreateInfo ci{XR_TYPE_INSTANCE_CREATE_INFO, &android};
    strcpy(ci.applicationInfo.applicationName, "Echo VR");
    ci.applicationInfo.applicationVersion = 4987566;
    strcpy(ci.applicationInfo.engineName, "EchoQuestXR");
    ci.applicationInfo.engineVersion = 1;
    ci.applicationInfo.apiVersion = XR_API_VERSION_1_0;   // Steam Frame's runtime is 1.0 only
    ci.enabledExtensionCount = (uint32_t)exts.size();
    ci.enabledExtensionNames = exts.data();
    if (!Ok(xrCreateInstance(&ci, &g.instance), "xrCreateInstance")) return -1;

    GetProc("xrGetVulkanInstanceExtensionsKHR", &g.getInstanceExts);
    GetProc("xrGetVulkanDeviceExtensionsKHR", &g.getDeviceExts);
    GetProc("xrGetVulkanGraphicsDeviceKHR", &g.getGraphicsDevice);
    GetProc("xrGetVulkanGraphicsRequirementsKHR", &g.getGraphicsRequirements);
    if (g.hasTimespec) {
        GetProc("xrConvertTimespecTimeToTimeKHR", &g.timespecToTime);
        GetProc("xrConvertTimeToTimespecTimeKHR", &g.timeToTimespec);
    }
    if (g.hasRefreshRate) {
        GetProc("xrEnumerateDisplayRefreshRatesFB", &g.enumerateRates);
        GetProc("xrGetDisplayRefreshRateFB", &g.getRate);
        GetProc("xrRequestDisplayRefreshRateFB", &g.requestRate);
    }

    XrInstanceProperties ip{XR_TYPE_INSTANCE_PROPERTIES};
    xrGetInstanceProperties(g.instance, &ip);
    XrSystemGetInfo si{XR_TYPE_SYSTEM_GET_INFO};
    si.formFactor = XR_FORM_FACTOR_HEAD_MOUNTED_DISPLAY;
    if (!Ok(xrGetSystem(g.instance, &si, &g.system), "xrGetSystem")) return -1;
    XrSystemProperties sp{XR_TYPE_SYSTEM_PROPERTIES};
    xrGetSystemProperties(g.instance, g.system, &sp);
    uint32_t views = 0;
    XrViewConfigurationView vcv[2] = { { XR_TYPE_VIEW_CONFIGURATION_VIEW }, { XR_TYPE_VIEW_CONFIGURATION_VIEW } };
    xrEnumerateViewConfigurationViews(g.instance, g.system, XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO, 2, &views, vcv);
    LOG("OpenXR runtime: %s %u.%u.%u, system '%s', eye %ux%u (max %ux%u)", ip.runtimeName,
        XR_VERSION_MAJOR(ip.runtimeVersion), XR_VERSION_MINOR(ip.runtimeVersion), XR_VERSION_PATCH(ip.runtimeVersion),
        sp.systemName, vcv[0].recommendedImageRectWidth, vcv[0].recommendedImageRectHeight,
        vcv[0].maxImageRectWidth, vcv[0].maxImageRectHeight);
    return vr::kSuccess;
}

EXPORT void vrapi_Shutdown() {
    for (Swapchain* s : g.swapchains) { DestroyFoveationMaps(s); xrDestroySwapchain(s->handle); delete s; }
    g.swapchains.clear();
    if (g.session) xrDestroySession(g.session);
    if (g.instance) xrDestroyInstance(g.instance);
    g.session = XR_NULL_HANDLE;
    g.instance = XR_NULL_HANDLE;
    LOG("shut down");
}

EXPORT const char* vrapi_GetVersionString() { return "1.1.40.0 (EchoQuestXR on OpenXR)"; }

EXPORT double vrapi_GetTimeInSeconds() { return Now(); }

// ---------------------------------------------------------------------------
// system properties (values Echo read on a Quest 3, or the runtime's)
// ---------------------------------------------------------------------------
float RefreshRate() {
    float r = 0;
    if (g.getRate && g.session && XR_SUCCEEDED(g.getRate(g.session, &r)) && r > 0) return r;
    return 1.0f / (float)g.period;
}

const std::vector<float>& RefreshRates() {
    if (g.rates.empty() && g.enumerateRates && g.session) {
        uint32_t n = 0;
        if (XR_SUCCEEDED(g.enumerateRates(g.session, 0, &n, nullptr)) && n) {
            g.rates.resize(n);
            g.enumerateRates(g.session, n, &n, g.rates.data());
        }
    }
    if (g.rates.empty()) g.rates = { RefreshRate() };
    return g.rates;
}

EXPORT int32_t vrapi_GetSystemPropertyInt(const vr::Java*, int32_t prop) {
    switch (prop) {
    case 0: return 320;   // device type: Quest 3 (keeps Echo on its Quest 3 settings)
    case 7: return 108;   // suggested eye FOV, degrees
    case 8: return 110;
    case 64: return (int32_t)RefreshRates().size();
    default: return 0;
    }
}

EXPORT float vrapi_GetSystemPropertyFloat(const vr::Java*, int32_t prop) {
    return prop == 4 ? RefreshRate() : 0.f;   // 4: display refresh rate
}

EXPORT int32_t vrapi_GetSystemPropertyFloatArray(const vr::Java*, int32_t prop, float* values, int32_t count) {
    if (prop != 65 || !values) return 0;   // 65: supported refresh rates
    const std::vector<float>& r = RefreshRates();
    int32_t n = std::min<int32_t>(count, (int32_t)r.size());
    for (int32_t i = 0; i < n; ++i) values[i] = r[i];
    return n;
}

EXPORT int32_t vrapi_GetSystemStatusInt(const vr::Java*, int32_t status) {
    return status == 1 ? 1 : 0;   // 1: headset mounted
}

// (java, property, int* value) -> found. Echo reads property 32 once (it was 1 on the Quest 3).
EXPORT int32_t vrapi_GetPropertyInt(const vr::Java*, int32_t prop, int32_t* value) {
    if (value) *value = prop == 32 ? 1 : 0;
    return prop == 32 ? 1 : 0;
}
EXPORT int32_t vrapi_SetPropertyInt(const vr::Java*, int32_t, int32_t) { return vr::kSuccess; }
EXPORT int32_t vrapi_SetClockLevels(void*, int32_t, int32_t) { return vr::kSuccess; }
EXPORT int32_t vrapi_SetExtraLatencyMode(void*, int32_t) { return vr::kSuccess; }
EXPORT int32_t vrapi_ShowSystemUI(const vr::Java*, int32_t) { return vr::kSuccess; }

EXPORT int32_t vrapi_SetDisplayRefreshRate(void*, float rate) {
    if (g.requestRate && g.session) {
        XrResult r = g.requestRate(g.session, rate);
        LOG("refresh rate %.0f requested: %d (now %.0f)", rate, (int)r, RefreshRate());
    }
    return vr::kSuccess;   // Steam Frame ignores the request; report success like the Quest does
}

// ---------------------------------------------------------------------------
// Vulkan
// ---------------------------------------------------------------------------
EXPORT int32_t vrapi_GetInstanceExtensionsVulkan(char* names, uint32_t* size) {
    std::string runtime;
    uint32_t n = 0;
    if (g.getInstanceExts && XR_SUCCEEDED(g.getInstanceExts(g.instance, g.system, 0, &n, nullptr)) && n) {
        runtime.resize(n);
        g.getInstanceExts(g.instance, g.system, n, &n, &runtime[0]);
        runtime.resize(strlen(runtime.c_str()));
    }
    std::string list = MergeExtensions("VK_KHR_surface VK_KHR_android_surface VK_KHR_external_memory_capabilities "
                                       "VK_KHR_get_physical_device_properties2", runtime);
    LOG("Vulkan instance extensions: %s", list.c_str());
    return WriteExtensions(list, names, size);
}

EXPORT int32_t vrapi_GetDeviceExtensionsVulkan(char* names, uint32_t* size) {
    std::string runtime;
    uint32_t n = 0;
    if (g.getDeviceExts && XR_SUCCEEDED(g.getDeviceExts(g.instance, g.system, 0, &n, nullptr)) && n) {
        runtime.resize(n);
        g.getDeviceExts(g.instance, g.system, n, &n, &runtime[0]);
        runtime.resize(strlen(runtime.c_str()));
    }
    std::string list = MergeExtensions("VK_KHR_swapchain VK_KHR_external_memory VK_KHR_get_memory_requirements2 "
                                       "VK_ANDROID_external_memory_android_hardware_buffer VK_EXT_queue_family_foreign "
                                       "VK_EXT_fragment_density_map", runtime);   // Echo renders with density maps
    LOG("Vulkan device extensions: %s", list.c_str());
    return WriteExtensions(list, names, size);
}

EXPORT int32_t vrapi_CreateSystemVulkan(vr::SystemCreateInfoVulkan* info) {
    if (!info || !g.instance) return vr::kErrorInvalidParameter;
    g.vkInstance = info->Instance;
    g.vkPhysical = info->PhysicalDevice;
    g.vkDevice = info->Device;
    if (g.getGraphicsRequirements) {
        XrGraphicsRequirementsVulkanKHR req{XR_TYPE_GRAPHICS_REQUIREMENTS_VULKAN_KHR};
        g.getGraphicsRequirements(g.instance, g.system, &req);
    }
    if (g.getGraphicsDevice) {
        VkPhysicalDevice want = VK_NULL_HANDLE;
        g.getGraphicsDevice(g.instance, g.system, g.vkInstance, &want);
        if (want != g.vkPhysical) LOGE("Echo's GPU %p isn't the one OpenXR wants (%p)", (void*)g.vkPhysical, (void*)want);
    }
    // the graphics queue family; EnterVrMode checks it against Echo's queue
    uint32_t n = 0;
    vkGetPhysicalDeviceQueueFamilyProperties(g.vkPhysical, &n, nullptr);
    std::vector<VkQueueFamilyProperties> fam(n);
    vkGetPhysicalDeviceQueueFamilyProperties(g.vkPhysical, &n, fam.data());
    for (uint32_t i = 0; i < n; ++i)
        if (fam[i].queueFlags & VK_QUEUE_GRAPHICS_BIT) { g.queueFamily = i; break; }
    return CreateSession() ? vr::kSuccess : vr::kErrorInvalidParameter;
}

EXPORT void vrapi_DestroySystemVulkan() {}

EXPORT void* vrapi_CreateTextureSwapChain3(int32_t type, int64_t format, int32_t width, int32_t height, int32_t levels,
                                           int32_t bufferCount) {
    if (!g.session) { LOGE("swapchain requested before the session exists"); return nullptr; }
    if (type != 0 && type != 2) { LOGE("swapchain type %d isn't supported", type); return nullptr; }
    auto* s = new Swapchain;
    XrSwapchainCreateInfo ci{XR_TYPE_SWAPCHAIN_CREATE_INFO};
    ci.usageFlags = XR_SWAPCHAIN_USAGE_COLOR_ATTACHMENT_BIT | XR_SWAPCHAIN_USAGE_SAMPLED_BIT | XR_SWAPCHAIN_USAGE_TRANSFER_DST_BIT;
    ci.format = format;   // a VkFormat (43 = VK_FORMAT_R8G8B8A8_SRGB)
    ci.sampleCount = 1;
    ci.width = (uint32_t)width;
    ci.height = (uint32_t)height;
    ci.faceCount = 1;
    ci.arraySize = type == 2 ? 2 : 1;   // 2D array: one layer per eye
    ci.mipCount = (uint32_t)std::max(1, levels);
    if (!Ok(xrCreateSwapchain(g.session, &ci, &s->handle), "xrCreateSwapchain")) { delete s; return nullptr; }
    uint32_t n = 0;
    xrEnumerateSwapchainImages(s->handle, 0, &n, nullptr);
    s->images.assign(n, { XR_TYPE_SWAPCHAIN_IMAGE_VULKAN_KHR });
    xrEnumerateSwapchainImages(s->handle, n, &n, reinterpret_cast<XrSwapchainImageBaseHeader*>(s->images.data()));
    s->width = width;
    s->height = height;
    s->arraySize = (int32_t)ci.arraySize;
    CreateFoveationMaps(s);
    g.swapchains.push_back(s);
    LOG("swapchain %p: %dx%d x%d, format %lld, %u images (Echo asked for %d)", (void*)s, width, height, s->arraySize,
        (long long)format, n, bufferCount);
    return s;
}

EXPORT void vrapi_DestroyTextureSwapChain(void* chain) {
    Swapchain* s = FindSwapchain(chain);
    if (!s) return;
    DestroyFoveationMaps(s);
    xrDestroySwapchain(s->handle);
    g.swapchains.erase(std::find(g.swapchains.begin(), g.swapchains.end(), s));
    delete s;
}

EXPORT int32_t vrapi_GetTextureSwapChainLength(void* chain) {
    Swapchain* s = FindSwapchain(chain);
    return s ? (int32_t)s->images.size() : 0;
}

EXPORT VkImage vrapi_GetTextureSwapChainBufferVulkan(void* chain, int32_t index) {
    Swapchain* s = FindSwapchain(chain);
    return s && index >= 0 && index < (int32_t)s->images.size() ? s->images[index].image : VK_NULL_HANDLE;
}

EXPORT int32_t vrapi_GetTextureSwapChainBufferFoveationVulkan(void* chain, int32_t index, VkImage* image, uint32_t* w, uint32_t* h) {
    Swapchain* s = FindSwapchain(chain);
    bool ok = s && index >= 0 && index < (int32_t)s->fdm.size() && s->fdm[index];
    if (image) *image = ok ? s->fdm[index] : VK_NULL_HANDLE;
    if (w) *w = ok ? s->fdmWidth : 0;
    if (h) *h = ok ? s->fdmHeight : 0;
    return ok ? vr::kSuccess : vr::kErrorNotImplemented;
}

// ---------------------------------------------------------------------------
// VR mode and events
// ---------------------------------------------------------------------------
EXPORT void* vrapi_EnterVrMode(const vr::ModeParmsVulkan* p) {
    if (!g.session) { LOGE("EnterVrMode without a session"); return nullptr; }
    if (p && p->SynchronizationQueue) {
        VkQueue q = VK_NULL_HANDLE;
        vkGetDeviceQueue(g.vkDevice, g.queueFamily, g.queueIndex, &q);
        if (q != p->SynchronizationQueue) LOGE("Echo renders on queue %p, OpenXR was given family %u queue %u (%p)",
                                                (void*)p->SynchronizationQueue, g.queueFamily, g.queueIndex, (void*)q);
    }
    g.wantRunning = true;
    // wait (up to 3 s) for the runtime to make the session READY
    for (int i = 0; i < 300 && !g.running; ++i) {
        PumpEvents();
        BeginSessionIfReady();
        if (!g.running) usleep(10000);
    }
    LOG("EnterVrMode: %s", g.running ? "running" : "not running yet");
    return &g;
}

EXPORT void vrapi_LeaveVrMode(void*) {
    // The runtime stops the session itself when Echo is paused (STOPPING -> xrEndSession);
    // keeping it lets EnterVrMode resume with the same swapchains.
    g.wantRunning = false;
    LOG("LeaveVrMode");
}

EXPORT int32_t vrapi_PollEvent(vr::EventHeader* event) {
    PumpEvents();
    if (!event) return vr::kErrorInvalidParameter;
    if (g.events.empty()) { event->EventType = vr::kEventNone; return vr::kSuccess; }
    event->EventType = g.events.front();
    g.events.pop_front();
    LOG("event %d", event->EventType);
    return vr::kSuccess;
}

// ---------------------------------------------------------------------------
// frames
// ---------------------------------------------------------------------------
// Echo asks for the display time of a frame before waiting on it: extrapolate from the
// last xrWaitFrame.
EXPORT double vrapi_GetPredictedDisplayTime(void*, int64_t frameIndex) {
    if (!g.waitedTime) return Now() + 2 * g.period;
    return g.waitedTime + ((double)frameIndex - (double)g.waitedIndex) * g.period;
}

EXPORT int32_t vrapi_WaitFrame(void* ovr, int64_t frameIndex) {
    if (!ovr) return vr::kErrorNotInitialized;
    PumpEvents();
    if (!g.running) { usleep((useconds_t)(g.period * 1e6)); return vr::kSuccess; }   // paused: don't spin
    if (g.waited && !g.begun) LOGE("frame %lld: waited twice", (long long)frameIndex);
    g.frame = { XR_TYPE_FRAME_STATE };
    if (!Ok(xrWaitFrame(g.session, nullptr, &g.frame), "xrWaitFrame")) return vr::kSuccess;
    g.waited = true;
    g.waitedIndex = (uint64_t)frameIndex;
    g.waitedTime = ToSeconds(g.frame.predictedDisplayTime);
    if (g.frame.predictedDisplayPeriod > 0) g.period = g.frame.predictedDisplayPeriod * 1e-9;
    return vr::kSuccess;
}

EXPORT int32_t vrapi_BeginFrame(void* ovr, int64_t frameIndex) {
    if (!ovr) return vr::kErrorNotInitialized;
    if (!g.running || !g.waited || g.begun) return vr::kSuccess;
    if (!Ok(xrBeginFrame(g.session, nullptr), "xrBeginFrame")) return vr::kSuccess;
    g.begun = true;
    // Echo picks its image itself, round-robin; OpenXR hands images out in its own
    // round-robin. Both go the same way, so if they're out of step (after a pause), hand
    // the image straight back and take the next until it's the one Echo will draw into.
    for (Swapchain* s : g.swapchains) {
        int32_t n = (int32_t)s->images.size();
        int32_t expect = n ? (s->echoLast + 1) % n : 0;
        for (int32_t tries = 0; tries < n; ++tries) {
            uint32_t idx = 0;
            if (!Ok(xrAcquireSwapchainImage(s->handle, nullptr, &idx), "xrAcquireSwapchainImage")) break;
            XrSwapchainImageWaitInfo wi{XR_TYPE_SWAPCHAIN_IMAGE_WAIT_INFO};
            wi.timeout = XR_INFINITE_DURATION;
            Ok(xrWaitSwapchainImage(s->handle, &wi), "xrWaitSwapchainImage");
            s->acquired = (int32_t)idx;
            if ((int32_t)idx == expect || tries == n - 1) break;
            XrSwapchainImageReleaseInfo ri{XR_TYPE_SWAPCHAIN_IMAGE_RELEASE_INFO};
            xrReleaseSwapchainImage(s->handle, &ri);
            s->acquired = -1;
        }
    }
    return vr::kSuccess;
}

EXPORT vr::Tracking2 vrapi_GetPredictedTracking2(void*, double seconds) {
    vr::Tracking2 out{};
    Locate(g.view, seconds, out.HeadPose, out.Status);
    XrView views[2] = { { XR_TYPE_VIEW }, { XR_TYPE_VIEW } };
    XrViewState vs{XR_TYPE_VIEW_STATE};
    uint32_t n = 0;
    bool ok = false;
    if (g.session) {
        XrViewLocateInfo li{XR_TYPE_VIEW_LOCATE_INFO};
        li.viewConfigurationType = XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO;
        li.displayTime = ToXrTime(seconds);
        li.space = g.local;
        ok = XR_SUCCEEDED(xrLocateViews(g.session, &li, &vs, 2, &n, views)) && n == 2 &&
             (vs.viewStateFlags & XR_VIEW_STATE_ORIENTATION_VALID_BIT);
    }
    for (int eye = 0; eye < 2; ++eye) {
        if (!ok) {   // something sane until tracking starts
            views[eye].pose = { { 0, 0, 0, 1 }, { eye ? 0.032f : -0.032f, 0, 0 } };
            views[eye].fov = { -0.82f, 0.82f, 0.82f, -0.82f };
        }
        out.Eye[eye].ProjectionMatrix = Projection(views[eye].fov);
        out.Eye[eye].ViewMatrix = ViewMatrix(views[eye].pose);
    }
    static double nextLog = 0;
    if (Now() >= nextLog) {
        nextLog = Now() + 30;
        const vr::Posef& h = out.HeadPose.Pose;
        LOG("tracking at %+.3fs: views %s (flags %llx), head status %x pos %.2f %.2f %.2f rot %.2f %.2f %.2f %.2f, eye0 fov %.2f/%.2f/%.2f/%.2f",
            seconds - Now(), ok ? "ok" : "FAILED", (unsigned long long)vs.viewStateFlags, out.Status, h.Position.x, h.Position.y,
            h.Position.z, h.Orientation.x, h.Orientation.y, h.Orientation.z, h.Orientation.w, views[0].fov.angleLeft,
            views[0].fov.angleRight, views[0].fov.angleUp, views[0].fov.angleDown);
    }
    ViewCache& c = g.cache[g.cacheNext];
    g.cacheNext = (g.cacheNext + 1) % 16;
    c.time = seconds;
    c.views[0] = views[0];
    c.views[1] = views[1];
    return out;
}

EXPORT int32_t vrapi_SubmitFrame2(void*, const vr::SubmitFrameDescription2* desc) {
    if (!g.begun) return vr::kSuccess;
    std::vector<XrCompositionLayerProjectionView> pv;
    std::vector<XrCompositionLayerProjection> projections;
    pv.reserve(8);
    projections.reserve(4);
    for (uint32_t i = 0; desc && i < desc->LayerCount && i < 4; ++i) {
        const vr::LayerHeader2* h = desc->Layers[i];
        if (!h) continue;
        if (h->Type != 1) {
            static bool warned = false;
            if (!warned) { warned = true; LOGE("layer type %d isn't supported (only projection)", h->Type); }
            continue;
        }
        const auto* l = reinterpret_cast<const vr::LayerProjection2*>(h);
        const ViewCache* c = FindViews(l->HeadPose.TimeInSeconds);
        size_t first = pv.size();
        for (int eye = 0; eye < 2; ++eye) {
            Swapchain* s = FindSwapchain(l->Textures[eye].ColorSwapChain);
            if (!s || !c) break;
            if (eye == 0) {
                s->echoLast = l->Textures[eye].SwapChainIndex;
                if (s->echoLast != s->acquired && s->mismatches++ < 10)
                    LOGE("Echo rendered image %d, OpenXR handed out %d", s->echoLast, s->acquired);
            }
            const float* r = l->Textures[eye].TextureRect;
            XrCompositionLayerProjectionView v{XR_TYPE_COMPOSITION_LAYER_PROJECTION_VIEW};
            v.pose = c->views[eye].pose;
            v.fov = c->views[eye].fov;
            if (g.flipY) std::swap(v.fov.angleUp, v.fov.angleDown);   // rows run bottom-up
            v.subImage.swapchain = s->handle;
            v.subImage.imageRect = { { (int32_t)(r[0] * s->width), (int32_t)(r[1] * s->height) },
                                     { (int32_t)(r[2] * s->width), (int32_t)(r[3] * s->height) } };
            v.subImage.imageArrayIndex = s->arraySize > 1 ? (uint32_t)eye : 0;
            pv.push_back(v);
        }
        if (pv.size() - first != 2) { pv.resize(first); continue; }
        XrCompositionLayerProjection p{XR_TYPE_COMPOSITION_LAYER_PROJECTION};
        p.space = g.local;
        p.viewCount = 2;
        p.views = &pv[first];
        projections.push_back(p);
    }
    for (Swapchain* s : g.swapchains)
        if (s->acquired >= 0) {
            if (g.testRed) PaintRed(s);
            if (g.testProbe && g.submitted % 72 == 0) Probe(s);
            XrSwapchainImageReleaseInfo ri{XR_TYPE_SWAPCHAIN_IMAGE_RELEASE_INFO};
            Ok(xrReleaseSwapchainImage(s->handle, &ri), "xrReleaseSwapchainImage");
            s->acquired = -1;
        }
    std::vector<const XrCompositionLayerBaseHeader*> layers;
    if (g.frame.shouldRender)
        for (auto& p : projections) layers.push_back(reinterpret_cast<const XrCompositionLayerBaseHeader*>(&p));
    XrFrameEndInfo ei{XR_TYPE_FRAME_END_INFO};
    ei.displayTime = g.frame.predictedDisplayTime;
    ei.environmentBlendMode = XR_ENVIRONMENT_BLEND_MODE_OPAQUE;
    ei.layerCount = (uint32_t)layers.size();
    ei.layers = layers.data();
    Ok(xrEndFrame(g.session, &ei), "xrEndFrame");
    g.begun = g.waited = false;
    if (++g.submitted == 1 || g.submitted % 720 == 0)
        LOG("frame %llu submitted (%zu layer(s), %.0f Hz, image mismatches so far %llu)", (unsigned long long)g.submitted,
            layers.size(), 1.0 / g.period, (unsigned long long)(g.swapchains.empty() ? 0 : g.swapchains[0]->mismatches));
    return vr::kSuccess;
}

// ---------------------------------------------------------------------------
// input: the two Touch controllers, as the Quest 3 reported them
// ---------------------------------------------------------------------------
EXPORT int32_t vrapi_EnumerateInputDevices(void*, uint32_t index, vr::InputCapabilityHeader* cap) {
    if (!cap) return vr::kErrorInvalidParameter;
    if (index > 1) return vr::kErrorDeviceUnavailable;   // no hand-tracking devices
    cap->Type = vr::kControllerTrackedRemote;
    cap->DeviceID = index ? vr::kDeviceRight : vr::kDeviceLeft;
    return vr::kSuccess;
}

EXPORT int32_t vrapi_GetInputDeviceCapabilities(void*, vr::InputCapabilityHeader* cap) {
    if (!cap) return vr::kErrorInvalidParameter;
    int hand = HandOf(cap->DeviceID);
    if (hand < 0 || cap->Type != vr::kControllerTrackedRemote) return vr::kErrorDeviceUnavailable;
    memcpy(reinterpret_cast<vr::InputTrackedRemoteCapabilities*>(cap)->Rest, kCapabilities[hand], 40);
    return vr::kSuccess;
}

EXPORT int32_t vrapi_GetCurrentInputState(void*, uint32_t deviceID, vr::InputStateTrackedRemote* st) {
    int hand = HandOf(deviceID);
    if (!st || hand < 0) return vr::kErrorDeviceUnavailable;
    SyncInput();
    vr::InputStateTrackedRemote s{};
    s.ControllerType = vr::kControllerTrackedRemote;
    s.TimeInSeconds = Now();
    s.BatteryPercent = 100;
    s.RecenterCount = g.recenterCount;
    if (g.session && g.focused) {
        bool left = hand == 0;
        float trig = Float(g.trigger, hand), grip = Float(g.grip, hand);
        XrVector2f stick = Vec2(g.stick, hand);
        bool primary = Bool(g.primary, hand), secondary = Bool(g.secondary, hand), click = Bool(g.stickClick, hand);
        bool tPrimary = Bool(g.primaryTouch, hand), tSecondary = Bool(g.secondaryTouch, hand);
        bool tStick = Bool(g.stickTouch, hand), tTrigger = Bool(g.triggerTouch, hand), tRest = Bool(g.thumbrest, hand);
        s.IndexTrigger = trig;
        s.GripTrigger = grip;
        s.Joystick[0] = s.JoystickNoDeadZone[0] = s.TrackpadPosition[0] = stick.x;
        s.Joystick[1] = s.JoystickNoDeadZone[1] = s.TrackpadPosition[1] = stick.y;
        uint32_t b = 0, t = 0;
        if (primary) b |= left ? vr::kButtonX : vr::kButtonA;
        if (secondary) b |= left ? vr::kButtonY : vr::kButtonB;
        if (click) b |= vr::kButtonJoystick | (left ? vr::kButtonLThumb : vr::kButtonRThumb);
        if (left && Bool(g.menu, hand)) b |= vr::kButtonEnter;
        if (trig > 0.1f) b |= vr::kButtonTrigger;
        if (grip > 0.1f) b |= vr::kButtonGrip;
        if (tPrimary) t |= left ? vr::kTouchX : vr::kTouchA;
        if (tSecondary) t |= left ? vr::kTouchY : vr::kTouchB;
        if (tStick) t |= vr::kTouchJoystick | (left ? vr::kTouchLThumb : vr::kTouchRThumb);
        if (tTrigger) t |= vr::kTouchIndexTrigger;
        else t |= vr::kTouchIndexPointing;
        if (tRest && left) t |= vr::kTouchLThumbRest;
        if (!(tPrimary || tSecondary || tStick || tRest)) t |= vr::kTouchThumbUp;
        s.Buttons = b;
        s.Touches = t;
    } else {
        s.Touches = vr::kTouchThumbUp | vr::kTouchIndexPointing;   // hands at rest
    }
    *st = s;
    return vr::kSuccess;
}

EXPORT int32_t vrapi_GetInputTrackingState(void*, uint32_t deviceID, double seconds, vr::Tracking* out) {
    int hand = HandOf(deviceID);
    if (!out || hand < 0) return vr::kErrorDeviceUnavailable;
    *out = {};
    // Echo also asks with a small float time (0 = "latest" in VrApi); it feeds its
    // hand-velocity history (throwing) from that call. Use now for anything implausible.
    if (std::fabs(seconds - Now()) > 5) {
        static int logged = 0;
        if (logged++ < 3) LOG("input tracking asked for time %.6f (now %.3f): using now", seconds, Now());
        seconds = Now();
    }
    Hand& h = g.hands[hand];
    vr::RigidBodyPosef& p = out->HeadPose;
    if (Locate(g.useAimPose ? h.aim : h.grip, seconds, p, out->Status)) {
        // Echo asks several times a frame for nearly the same time; update on a real step
        double dt = seconds - h.lastTime;
        if (dt > 0.004 && dt < 0.1) {
            const float k = 0.5f;   // smoothing: half new, half old
            auto acc = [&](vr::Vector3f& a, const vr::Vector3f& now, const vr::Vector3f& before) {
                a.x += k * ((float)((now.x - before.x) / dt) - a.x);
                a.y += k * ((float)((now.y - before.y) / dt) - a.y);
                a.z += k * ((float)((now.z - before.z) / dt) - a.z);
            };
            acc(h.linearAccel, p.LinearVelocity, h.lastLinear);
            acc(h.angularAccel, p.AngularVelocity, h.lastAngular);
        }
        if (dt > 0.004 || dt < 0) {
            h.lastTime = seconds;
            h.lastLinear = p.LinearVelocity;
            h.lastAngular = p.AngularVelocity;
        }
        p.LinearAcceleration = h.linearAccel;
        p.AngularAcceleration = h.angularAccel;
        const vr::Vector3f& v = p.LinearVelocity;
        h.peakSpeed = std::max(h.peakSpeed, std::sqrt((double)(v.x * v.x + v.y * v.y + v.z * v.z)));
        static double nextLog = 0;
        if (hand == 1 && Now() >= nextLog) {
            nextLog = Now() + 2;
            LOG("hand speed (peak, m/s): left %.2f right %.2f", g.hands[0].peakSpeed, g.hands[1].peakSpeed);
            g.hands[0].peakSpeed = g.hands[1].peakSpeed = 0;
        }
    }
    return vr::kSuccess;
}

EXPORT int32_t vrapi_SetHapticVibrationBuffer(void*, uint32_t deviceID, const vr::HapticBuffer* buf) {
    int hand = HandOf(deviceID);
    if (hand < 0 || !buf || !g.session || !g.focused) return vr::kSuccess;
    uint32_t n = std::min<uint32_t>(buf->NumSamples, 1000);
    uint8_t peak = 0;
    for (uint32_t i = 0; buf->Samples && i < n; ++i) peak = std::max(peak, buf->Samples[i]);
    XrHapticActionInfo hi{XR_TYPE_HAPTIC_ACTION_INFO};
    hi.action = g.haptic;
    hi.subactionPath = g.hands[hand].path;
    if (!peak) { xrStopHapticFeedback(g.session, &hi); return vr::kSuccess; }
    XrHapticVibration v{XR_TYPE_HAPTIC_VIBRATION};
    v.amplitude = peak / 255.f;
    v.duration = (XrDuration)n * 2000000;   // 2 ms per sample (the controllers' capabilities say so)
    v.frequency = XR_FREQUENCY_UNSPECIFIED;
    xrApplyHapticFeedback(g.session, &hi, reinterpret_cast<const XrHapticBaseHeader*>(&v));
    return vr::kSuccess;
}

// The loader's API-level marker (exported by Meta's loader as a C++ function).
__attribute__((visibility("default"))) void VRAPI_LOADER_API_LEVEL_V23() {}
