"""Generates the logger's per-export assembly stubs and name table from exports.txt.

    python gen_stubs.py            writes stubs.S and names.h next to this script

exports.txt is every function libvrapi.so exports (llvm-readelf --dyn-syms on Meta's
VrApi loader 1.1.40 from the Echo VR Quest APK). Each stub loads its index into x16 and
jumps to the shared trampoline in stubs.S, so the logger forwards every call without
needing VrApi's headers: argument and return registers pass through untouched.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
names = [l.strip() for l in open(os.path.join(HERE, "exports.txt")) if l.strip()]

TRAMPOLINE = r"""
// Shared trampoline. Frame layout (struct VrFrame in vrapi_logger.c):
//   [0]   x0-x7 arguments      [64]  x8 (indirect result pointer)
//   [80]  q0-q7 arguments      [208] x29, x30 (frame record)
//   [224] export index         [232] "this call is logged" flag (set by __vrlog_enter)
//   [240] x0, x1 return        [256] q0-q3 return
// VrApi functions take at most six arguments, none on the stack, so moving sp is safe.
    .text
    .p2align 2
    .type __vrlog_common, %function
__vrlog_common:
    sub  sp, sp, #320
    stp  x0, x1, [sp, #0]
    stp  x2, x3, [sp, #16]
    stp  x4, x5, [sp, #32]
    stp  x6, x7, [sp, #48]
    str  x8, [sp, #64]
    stp  q0, q1, [sp, #80]
    stp  q2, q3, [sp, #112]
    stp  q4, q5, [sp, #144]
    stp  q6, q7, [sp, #176]
    stp  x29, x30, [sp, #208]
    add  x29, sp, #208
    str  x16, [sp, #224]
    mov  w0, w16
    mov  x1, sp
    bl   __vrlog_enter              // logs the call, returns the real function
    mov  x17, x0
    ldp  x0, x1, [sp, #0]
    ldp  x2, x3, [sp, #16]
    ldp  x4, x5, [sp, #32]
    ldp  x6, x7, [sp, #48]
    ldr  x8, [sp, #64]
    ldp  q0, q1, [sp, #80]
    ldp  q2, q3, [sp, #112]
    ldp  q4, q5, [sp, #144]
    ldp  q6, q7, [sp, #176]
    blr  x17
    stp  x0, x1, [sp, #240]
    stp  q0, q1, [sp, #256]
    stp  q2, q3, [sp, #288]
    ldr  x0, [sp, #224]
    mov  x1, sp
    bl   __vrlog_exit               // logs the result
    ldp  x0, x1, [sp, #240]
    ldp  q0, q1, [sp, #256]
    ldp  q2, q3, [sp, #288]
    ldp  x29, x30, [sp, #208]
    add  sp, sp, #320
    ret
    .size __vrlog_common, .-__vrlog_common
"""

with open(os.path.join(HERE, "stubs.S"), "w", newline="\n") as f:
    f.write("// Generated by gen_stubs.py from exports.txt -- do not edit.\n")
    f.write(TRAMPOLINE)
    for i, n in enumerate(names):
        f.write(f"""
    .p2align 2
    .globl {n}
    .type {n}, %function
{n}:
    mov  x16, #{i}
    b    __vrlog_common
    .size {n}, .-{n}
""")
    f.write('\n    .section .note.GNU-stack,"",%progbits\n')

with open(os.path.join(HERE, "names.h"), "w", newline="\n") as f:
    f.write("// Generated by gen_stubs.py from exports.txt -- do not edit.\n")
    f.write(f"#define VRLOG_COUNT {len(names)}\n")
    f.write("static const char* const kVrNames[VRLOG_COUNT] = {\n")
    for n in names:
        f.write(f'    "{n}",\n')
    f.write("};\n")
print(f"{len(names)} exports -> stubs.S, names.h")
