// EchoQuestXR VrApi logger -- a stand-in libvrapi.so that logs every VrApi call Echo VR
// (Quest) makes, then forwards it to Meta's real loader, renamed libvrapi_real.so in the
// APK. The log is the to-do list for an OpenXR implementation of the same functions.
//
//   adb logcat -s EchoQuestXR
//
// Every export is an assembly stub (stubs.S, generated by gen_stubs.py) that saves the
// argument registers and calls __vrlog_enter / __vrlog_exit around the real function, so
// calls pass through untouched without VrApi's headers. What gets logged:
//   * the first few calls of every function, with raw arguments and return value;
//   * setup calls always, decoded where it helps (Vulkan extensions, system
//     properties, swapchains, input devices, events, refresh rate, clocks);
//   * every 5 s, how many times each function was called -- the per-frame rhythm.
// Struct contents are hex dumps: VrApi's headers aren't used, so layouts are read
// from the dumps.
#define _GNU_SOURCE
#include <android/log.h>
#include <dlfcn.h>
#include <math.h>
#include <pthread.h>
#include <stdatomic.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <sys/uio.h>
#include <time.h>
#include <unistd.h>

#include "names.h"

#define TAG "EchoQuestXR"
#define LOG(...) __android_log_print(ANDROID_LOG_INFO, TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, TAG, __VA_ARGS__)

typedef union { __uint128_t u; float f; double d; uint64_t lo; } VReg;
typedef struct {
    uint64_t x[8];      // 0   argument registers
    uint64_t x8;        // 64  indirect result pointer (structs returned by value)
    uint64_t pad;       // 72
    VReg     q[8];      // 80  float/vector argument registers
    uint64_t fp, lr;    // 208
    uint64_t idx;       // 224
    uint64_t logged;    // 232 set by __vrlog_enter, read by __vrlog_exit
    uint64_t r[2];      // 240 return registers
    VReg     rq[4];     // 256
} VrFrame;
_Static_assert(offsetof(VrFrame, q) == 80 && offsetof(VrFrame, idx) == 224 &&
               offsetof(VrFrame, r) == 240 && offsetof(VrFrame, rq) == 256 && sizeof(VrFrame) == 320,
               "VrFrame must match the trampoline in stubs.S");

static void* g_real[VRLOG_COUNT];
static atomic_uint g_calls[VRLOG_COUNT];      // since start
static atomic_uint g_interval[VRLOG_COUNT];   // since the last summary
static pthread_once_t g_once = PTHREAD_ONCE_INIT;
static double g_start;

static double Now(void) {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return ts.tv_sec + ts.tv_nsec * 1e-9;
}

static uint64_t Missing(void) { return 0; }   // a function the real loader doesn't have

static void LoadReal(void) {
    g_start = Now();
    void* h = dlopen("libvrapi_real.so", RTLD_NOW | RTLD_LOCAL);
    if (!h) { LOGE("can't load libvrapi_real.so: %s", dlerror()); return; }
    int missing = 0;
    for (int i = 0; i < VRLOG_COUNT; ++i)
        if (!(g_real[i] = dlsym(h, kVrNames[i]))) ++missing;
    LOG("forwarding to libvrapi_real.so: %d of %d functions found", VRLOG_COUNT - missing, VRLOG_COUNT);
}

__attribute__((constructor)) static void Loaded(void) {
    LOG("VrApi logger loaded into pid %d", getpid());
}

// ---------------------------------------------------------------------------
// which calls to log
// ---------------------------------------------------------------------------
static int Is(uint32_t idx, const char* name) { return !strcmp(kVrNames[idx], name); }
static int StartsWith(uint32_t idx, const char* p) { return !strncmp(kVrNames[idx], p, strlen(p)); }

// how many calls of this function to log in full
static unsigned Limit(uint32_t idx) {
    if (Is(idx, "vrapi_PollEvent")) return 0;   // logged at exit, only when there's an event
    if (StartsWith(idx, "vrapi_GetSystemProperty") || StartsWith(idx, "vrapi_GetSystemStatus") ||
        Is(idx, "vrapi_GetPropertyInt") || Is(idx, "vrapi_SetPropertyInt") ||
        Is(idx, "vrapi_EnumerateInputDevices") || Is(idx, "vrapi_GetInputDeviceCapabilities") ||
        StartsWith(idx, "vrapi_CreateTextureSwapChain") || Is(idx, "vrapi_DestroyTextureSwapChain") ||
        Is(idx, "vrapi_GetTextureSwapChainLength") || Is(idx, "vrapi_SetDisplayRefreshRate") ||
        Is(idx, "vrapi_SetClockLevels") || Is(idx, "vrapi_SetExtraLatencyMode") || Is(idx, "vrapi_ShowSystemUI"))
        return 200;
    if (Is(idx, "vrapi_GetTextureSwapChainBufferVulkan") || Is(idx, "vrapi_GetTextureSwapChainBufferFoveationVulkan"))
        return 64;   // once per swapchain image at setup
    if (Is(idx, "vrapi_WaitFrame") || Is(idx, "vrapi_BeginFrame") || StartsWith(idx, "vrapi_SubmitFrame") ||
        Is(idx, "vrapi_GetPredictedDisplayTime") || StartsWith(idx, "vrapi_GetPredictedTracking") ||
        Is(idx, "vrapi_GetTimeInSeconds") || Is(idx, "vrapi_GetCurrentInputState") ||
        Is(idx, "vrapi_GetInputTrackingState") || Is(idx, "vrapi_SetHapticVibrationBuffer"))
        return 4;    // per frame: the first few, then the summary counts
    return 50;       // setup and everything else
}

// Copies from this process's memory without ever faulting: the kernel reports a bad
// address (EFAULT) instead of the game crashing on a pointer we guessed wrong.
static int SafeCopy(void* dst, const void* src, size_t n) {
    struct iovec local = { dst, n }, remote = { (void*)src, n };
    return src && (uintptr_t)src >= 0x10000 && process_vm_readv(getpid(), &local, 1, &remote, 1, 0) == (ssize_t)n;
}

static void Hex(const char* what, const void* p, int n) {
    uint8_t b[400];
    if (n > (int)sizeof(b)) n = sizeof(b);
    if (!SafeCopy(b, p, n)) { LOG("    %s: unreadable (%p)", what, p); return; }
    char line[3 * 96 + 1];
    for (int off = 0; off < n; off += 32) {
        int k = n - off < 32 ? n - off : 32, w = 0;
        for (int i = 0; i < k; ++i) w += snprintf(line + w, sizeof(line) - w, "%02x ", b[off + i]);
        LOG("    %s +%02x: %s", what, off, line);
    }
}

static void Summary(void) {
    static atomic_long nextAt;   // ms since start
    long now = (long)((Now() - g_start) * 1000), due = atomic_load(&nextAt);
    if (now < due || !atomic_compare_exchange_strong(&nextAt, &due, now + 5000)) return;
    char line[900];
    int w = 0;
    for (int i = 0; i < VRLOG_COUNT; ++i) {
        unsigned n = atomic_exchange(&g_interval[i], 0);
        if (!n) continue;
        w += snprintf(line + w, sizeof(line) - w, "%s %u, ", kVrNames[i] + (StartsWith(i, "vrapi_") ? 6 : 0), n);
        if (w > (int)sizeof(line) - 80) { LOG("calls in 5 s: %s", line); w = 0; }
    }
    if (w) LOG("calls in 5 s: %s", line);
}

// ---------------------------------------------------------------------------
// enter / exit (called from the trampoline)
// ---------------------------------------------------------------------------
void* __vrlog_enter(uint32_t idx, VrFrame* f) {
    pthread_once(&g_once, LoadReal);
    unsigned n = atomic_fetch_add(&g_calls[idx], 1) + 1;
    atomic_fetch_add(&g_interval[idx], 1);
    f->logged = n <= Limit(idx);
    if (f->logged) {
        LOG("[%.3f t%d] %s #%u (x0=%llx x1=%llx x2=%llx x3=%llx x4=%llx x5=%llx | s0=%g d0=%g)",
            Now() - g_start, gettid(), kVrNames[idx], n,
            (unsigned long long)f->x[0], (unsigned long long)f->x[1], (unsigned long long)f->x[2],
            (unsigned long long)f->x[3], (unsigned long long)f->x[4], (unsigned long long)f->x[5],
            f->q[0].f, f->q[0].d);
        const void* a0 = (const void*)f->x[0];
        const void* a1 = (const void*)f->x[1];
        if (Is(idx, "vrapi_Initialize")) Hex("ovrInitParms", a0, 96);
        else if (Is(idx, "vrapi_EnterVrMode")) Hex("ovrModeParms", a0, 128);
        else if (Is(idx, "vrapi_CreateSystemVulkan")) Hex("ovrSystemCreateInfoVulkan", a0, 32);
        else if (StartsWith(idx, "vrapi_SubmitFrame")) {
            Hex("submit desc", a1, 96);
            // the first layer: desc+0x28 -> array of layer pointers -> layer
            const void* layers = NULL;
            const void* layer0 = NULL;
            if (SafeCopy(&layers, (const char*)a1 + 0x28, sizeof(layers)) && SafeCopy(&layer0, layers, sizeof(layer0)))
                Hex("layer 0", layer0, 336);
        }
    }
    Summary();
    return g_real[idx] ? g_real[idx] : (void*)Missing;
}

// Button mapping: logs a controller's input state whenever it changes, showing only the
// 4-byte words that changed (as hex and as a float). The two controllers' states sit 72
// bytes apart in Echo's memory, so 72 bytes cover the whole struct; bytes 8-15 are the
// timestamp and skipped. Analog changes under 0.05 are ignored, so resting jitter is quiet.
#define INPUT_BYTES 72
static int LooksFloat(uint32_t w) {
    float v;
    memcpy(&v, &w, 4);
    return w == 0 || (v > -2.f && v < 2.f && (v > 1e-4f || v < -1e-4f));
}
static void InputChanged(const VrFrame* f) {
    static uint8_t last[2][INPUT_BYTES];
    static int have[2];
    int side = f->x[1] == 0x20000002 ? 0 : f->x[1] == 0x20000003 ? 1 : -1;
    uint8_t now[INPUT_BYTES];
    if (side < 0 || (int)f->r[0] != 0 || !SafeCopy(now, (const void*)f->x[2], sizeof(now))) return;
    if (!have[side]) { memcpy(last[side], now, sizeof(now)); have[side] = 1; Hex(side ? "R input (first)" : "L input (first)", now, INPUT_BYTES); return; }
    char line[700];
    int w = 0;
    for (int off = 0; off < INPUT_BYTES; off += 4) {
        if (off == 8 || off == 12) continue;   // timestamp
        uint32_t a, b;
        memcpy(&a, last[side] + off, 4);
        memcpy(&b, now + off, 4);
        if (a == b) continue;
        float fa, fb;
        memcpy(&fa, &a, 4);
        memcpy(&fb, &b, 4);
        if (LooksFloat(a) && LooksFloat(b) && fabsf(fb - fa) < 0.05f) continue;   // analog jitter
        w += snprintf(line + w, sizeof(line) - w, " +%02x %08x->%08x (%.2f)", off, a, b, fb);
        memcpy(last[side] + off, now + off, 4);
        if (w > (int)sizeof(line) - 60) break;
    }
    if (w) LOG("[%.3f] %s input:%s", Now() - g_start, side ? "R" : "L", line);
}

void __vrlog_exit(uint32_t idx, VrFrame* f) {
    if (Is(idx, "vrapi_GetCurrentInputState")) InputChanged(f);
    const void* a0 = (const void*)f->x[0];
    const void* a1 = (const void*)f->x[1];
    const void* a2 = (const void*)f->x[2];
    if (Is(idx, "vrapi_PollEvent")) {   // only real events
        static atomic_uint shown;
        int type = 0;
        if ((int)f->r[0] == 0 && SafeCopy(&type, a0, sizeof(type)) && type != 0 && atomic_fetch_add(&shown, 1) < 500) {
            LOG("[%.3f] event type %d", Now() - g_start, type);
            Hex("event", a0, 32);
        }
        return;
    }
    if (!f->logged) return;
    LOG("  -> %s = %llx (int %d, s0=%g, d0=%g)", kVrNames[idx], (unsigned long long)f->r[0], (int)f->r[0],
        f->rq[0].f, f->rq[0].d);
    if (Is(idx, "vrapi_GetInstanceExtensionsVulkan") || Is(idx, "vrapi_GetDeviceExtensionsVulkan")) {
        // (char* names, uint32_t* size): space-separated extension names
        if (a0) LOG("     extensions: %.*s", f->x[1] ? (int)*(const uint32_t*)a1 : 1024, (const char*)a0);
        if (a1) LOG("     size: %u", *(const uint32_t*)a1);
    } else if (Is(idx, "vrapi_GetVersionString")) {
        if (f->r[0]) LOG("     version: %s", (const char*)f->r[0]);
    } else if (Is(idx, "vrapi_GetSystemPropertyInt") || Is(idx, "vrapi_GetSystemStatusInt")) {
        LOG("     property %llu = %d", (unsigned long long)f->x[1], (int)f->r[0]);
    } else if (Is(idx, "vrapi_GetSystemPropertyFloat")) {
        LOG("     property %llu = %g", (unsigned long long)f->x[1], f->rq[0].f);
    } else if (Is(idx, "vrapi_GetSystemPropertyFloatArray")) {
        // (java, property, float* values, int count) -> count written
        int n = (int)f->r[0];
        char line[400];
        int w = 0;
        for (int i = 0; a2 && i < n && i < 24; ++i) w += snprintf(line + w, sizeof(line) - w, "%g ", ((const float*)a2)[i]);
        LOG("     property %llu = [%d] %s", (unsigned long long)f->x[1], n, w ? line : "");
    } else if (StartsWith(idx, "vrapi_GetPredictedTracking")) {
        Hex("tracking (returned)", (const void*)f->x8, 360);
    } else if (Is(idx, "vrapi_GetInputTrackingState")) {
        // (ovr, deviceID, double time, ovrTracking* out): the double is in d0, so out is x2
        Hex("input tracking", a2, 96);
    } else if (Is(idx, "vrapi_EnumerateInputDevices")) {
        if ((int)f->r[0] == 0) Hex("capability header", a2, 16);
    } else if (Is(idx, "vrapi_GetInputDeviceCapabilities")) {
        Hex("capabilities", a1, 96);
    } else if (Is(idx, "vrapi_GetCurrentInputState")) {
        Hex("input state", a2, 128);
    } else if (Is(idx, "vrapi_CreateSystemVulkan")) {
        Hex("ovrSystemCreateInfoVulkan (after)", a0, 32);
    }
}
